const IOT = {
        color: "#3CF527",
        subtopics: {
            "Mix all questions": {
                color: "#3CF527",
                questions: [
                    { id: 1, question: "Which of the following best defines IoT?", options: ["Connecting computers to the internet", "Connecting everyday objects to the internet", "Creating websites for devices", "Developing mobile applications"], correct: 2 },
                    { id: 2, question: "Which communication protocol is most commonly used in IoT devices?", options: ["HTTP", "MQTT", "SMTP", "FTP"], correct: 2 },
                    { id: 3, question: "What does RFID stand for in IoT?", options: ["Radio Frequency Identification", "Remote Frequency Identification", "Radio File Identification", "Remote File Identification"], correct: 1 },
                    { id: 4, question: "Which layer of IoT architecture deals with data storage and processing?", options: ["Perception Layer", "Network Layer", "Application Layer", "Middleware Layer"], correct: 4 },
                    { id: 5, question: "Which of the following is an IoT cloud platform?", options: ["Google Firebase", "AWS IoT Core", "Microsoft Azure IoT", "All of the above"], correct: 4 },
                    { id: 6, question: "What is the main function of sensors in IoT devices?", options: ["Store data", "Collect data", "Process data", "Transmit data"], correct: 2 },
                    { id: 7, question: "Which of the following is an application of IoT in healthcare?", options: ["Smart watches", "Remote patient monitoring", "Online appointment booking", "Medical transcription"], correct: 2 },
                    { id: 8, question: "Which network is commonly used for IoT low-power communication?", options: ["4G LTE", "Wi-Fi", "LoRaWAN", "Ethernet"], correct: 3 },
                    { id: 9, question: "What is the main challenge in IoT security?", options: ["Limited devices", "Limited bandwidth", "Large attack surface", "Expensive sensors"], correct: 3 },
                    { id: 10, question: "In IoT, actuators are used to:", options: ["Display information", "Collect data", "Perform actions", "Transmit data"], correct: 3 },

                    { id: 11, question: "Which protocol is lightweight and commonly used in IoT messaging?", options: ["SMTP", "FTP", "MQTT", "SSH"], correct: 3 },
                    { id: 12, question: "Which of the following is an IoT-enabled home device?", options: ["Smart refrigerator", "Desktop computer", "Laser printer", "Washing powder"], correct: 1 },
                    { id: 13, question: "What does NFC stand for?", options: ["Near Field Communication", "Network Field Communication", "Near Frequency Communication", "Network Frequency Communication"], correct: 1 },
                    { id: 14, question: "Which is NOT an application of IoT?", options: ["Smart homes", "Smart agriculture", "Smart parking", "Word processing"], correct: 4 },
                    { id: 15, question: "Which layer ensures connectivity in IoT?", options: ["Perception Layer", "Network Layer", "Application Layer", "Business Layer"], correct: 2 },
                    { id: 16, question: "Which device is often called the ‘heart’ of IoT systems?", options: ["Router", "Gateway", "Sensor", "Database"], correct: 2 },
                    { id: 17, question: "Which wireless technology is most suitable for short-range IoT communication?", options: ["Zigbee", "LoRa", "5G", "Ethernet"], correct: 1 },
                    { id: 18, question: "Which of these IoT applications relates to transportation?", options: ["Smart traffic management", "Online shopping", "Mobile banking", "Social networking"], correct: 1 },
                    { id: 19, question: "What is the full form of CoAP?", options: ["Constrained Application Protocol", "Connected Application Protocol", "Central Access Protocol", "Control Application Protocol"], correct: 1 },
                    { id: 20, question: "Which of the following is a security measure for IoT?", options: ["Encryption", "Firewalls", "Authentication", "All of the above"], correct: 4 },

                    { id: 21, question: "Which technology is essential for IoT scalability?", options: ["Cloud computing", "LAN", "Bluetooth", "Flash drives"], correct: 1 },
                    { id: 22, question: "IoT devices are usually constrained by:", options: ["High storage", "High speed", "Low power", "Large memory"], correct: 3 },
                    { id: 23, question: "Which of these is a wearable IoT device?", options: ["Smartwatch", "Router", "Laptop", "USB drive"], correct: 1 },
                    { id: 24, question: "Which IoT communication protocol is based on publish-subscribe model?", options: ["HTTP", "MQTT", "FTP", "Telnet"], correct: 2 },
                    { id: 25, question: "Which of these is an industrial IoT application?", options: ["Predictive maintenance", "Smart cooking", "Online video streaming", "Word editing"], correct: 1 },
                    { id: 26, question: "IoT devices usually connect to the cloud via:", options: ["Ethernet only", "Mobile apps", "Gateways", "Databases"], correct: 3 },
                    { id: 27, question: "In IoT, edge computing helps by:", options: ["Reducing latency", "Storing huge data centrally", "Replacing sensors", "Removing gateways"], correct: 1 },
                    { id: 28, question: "Which of the following is an IoT protocol for resource-constrained devices?", options: ["FTP", "SMTP", "CoAP", "POP3"], correct: 3 },
                    { id: 29, question: "IoT is an integration of:", options: ["Hardware only", "Software only", "Hardware and software with internet", "None of these"], correct: 3 },
                    { id: 30, question: "Which of these technologies will boost IoT growth?", options: ["5G", "Dial-up internet", "Floppy disks", "CRT monitors"], correct: 1 },

                    { id: 31, question: "Which of these is an IoT healthcare device?", options: ["ECG monitoring device", "Typewriter", "Projector", "Printer"], correct: 1 },
                    { id: 32, question: "Which of these communication technologies has low power consumption?", options: ["LoRa", "Fiber optic", "Ethernet", "Coaxial cable"], correct: 1 },
                    { id: 33, question: "What does the perception layer in IoT do?", options: ["Collects data via sensors", "Processes data", "Transmits data", "Provides applications"], correct: 1 },
                    { id: 34, question: "Which IoT application is related to agriculture?", options: ["Crop monitoring", "E-learning", "Social media", "Movie streaming"], correct: 1 },
                    { id: 35, question: "Which wireless technology is often used in smart home IoT devices?", options: ["Zigbee", "Ethernet", "Token Ring", "DSL"], correct: 1 },
                    { id: 36, question: "What is the role of actuators in IoT?", options: ["Sense data", "Perform physical actions", "Transmit packets", "Store data"], correct: 2 },
                    { id: 37, question: "Which IoT application improves city infrastructure?", options: ["Smart parking", "Word processing", "Desktop publishing", "File transfer"], correct: 1 },
                    { id: 38, question: "IoT devices often use which addressing scheme?", options: ["IPv4", "IPv6", "MAC addresses only", "Binary codes"], correct: 2 },
                    { id: 39, question: "What is the biggest concern in IoT networks?", options: ["Security", "Color display", "High speed", "Large screens"], correct: 1 },
                    { id: 40, question: "Which IoT device uses biometric data?", options: ["Smartwatch", "Printer", "Scanner", "Keyboard"], correct: 1 },

                    { id: 41, question: "Which company provides 'AWS IoT Core'?", options: ["Google", "Amazon", "Microsoft", "IBM"], correct: 2 },
                    { id: 42, question: "Which wireless technology is suitable for IoT device-to-device communication?", options: ["Bluetooth", "Ethernet", "DSL", "ISDN"], correct: 1 },
                    { id: 43, question: "Which protocol is commonly used in IoT device management?", options: ["SNMP", "SMTP", "IMAP", "POP"], correct: 1 },
                    { id: 44, question: "Which of the following IoT applications is in the energy sector?", options: ["Smart grids", "Social media", "Word processors", "Gaming"], correct: 1 },
                    { id: 45, question: "Which of these enables remote control of IoT devices?", options: ["Mobile apps", "CD drives", "Printers", "Scanners"], correct: 1 },
                    { id: 46, question: "IoT devices often require which type of IP?", options: ["Static IP", "Dynamic IP", "Both Static and Dynamic", "No IP"], correct: 3 },
                    { id: 47, question: "Which of these is a low-power short-range IoT protocol?", options: ["Zigbee", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 48, question: "Which industry uses IoT for supply chain tracking?", options: ["Logistics", "Education", "Entertainment", "Tourism"], correct: 1 },
                    { id: 49, question: "What is the function of IoT middleware?", options: ["Application interface", "Data processing and management", "Device replacement", "Web browsing"], correct: 2 },
                    { id: 50, question: "Which of these is NOT a challenge in IoT?", options: ["Security", "Scalability", "Low bandwidth", "Desktop publishing"], correct: 4 },
                    { id: 51, question: "Which IoT application helps in reducing electricity usage?", options: ["Smart lighting", "Text editors", "Printers", "File compression"], correct: 1 },
                    { id: 52, question: "Which of these is NOT a communication protocol in IoT?", options: ["MQTT", "CoAP", "SMTP", "XHTML"], correct: 4 },
                    { id: 53, question: "Which of the following is an example of smart city IoT?", options: ["Smart parking", "Smart traffic lights", "Smart waste management", "All of the above"], correct: 4 },
                    { id: 54, question: "What is the role of gateways in IoT?", options: ["Connect IoT devices to the cloud", "Provide electricity", "Store files", "Design websites"], correct: 1 },
                    { id: 55, question: "Which one is a security risk in IoT?", options: ["Default passwords", "Encryption", "Authentication", "Firewall"], correct: 1 },
                    { id: 56, question: "Which of these is NOT an IoT enabling technology?", options: ["AI", "Cloud computing", "Big data", "Typewriter"], correct: 4 },
                    { id: 57, question: "Which of the following is an IoT wearable?", options: ["Fitness tracker", "Keyboard", "Monitor", "Printer"], correct: 1 },
                    { id: 58, question: "Which IoT application is related to environment monitoring?", options: ["Air quality sensors", "Music apps", "E-books", "Video players"], correct: 1 },
                    { id: 59, question: "IoT devices mostly work with which type of data?", options: ["Structured data only", "Unstructured data only", "Both structured and unstructured data", "No data"], correct: 3 },
                    { id: 60, question: "Which of these is an IoT healthcare application?", options: ["Smart insulin pump", "Calculator", "Gaming console", "Scanner"], correct: 1 },

                    { id: 61, question: "Which of the following is an IoT standard protocol?", options: ["Zigbee", "SMTP", "POP3", "Telnet"], correct: 1 },
                    { id: 62, question: "IoT systems usually consist of:", options: ["Sensors, connectivity, data processing, applications", "Only sensors", "Only networks", "Only applications"], correct: 1 },
                    { id: 63, question: "Which wireless technology has the widest coverage for IoT?", options: ["Bluetooth", "Wi-Fi", "LoRa", "Zigbee"], correct: 3 },
                    { id: 64, question: "Which IoT application is useful in disaster management?", options: ["Flood detection sensors", "File transfer apps", "Photo editing apps", "Games"], correct: 1 },
                    { id: 65, question: "Which of the following is NOT an IoT device?", options: ["Smart thermostat", "Smart bulb", "Smart fridge", "Word processor"], correct: 4 },
                    { id: 66, question: "Which technology allows IoT devices to make intelligent decisions?", options: ["Artificial Intelligence", "Text processing", "Database indexing", "CRT display"], correct: 1 },
                    { id: 67, question: "Which protocol is widely used for constrained IoT devices?", options: ["CoAP", "HTTP", "FTP", "SMTP"], correct: 1 },
                    { id: 68, question: "What does an actuator do in IoT?", options: ["Stores data", "Senses the environment", "Takes actions", "Manages connectivity"], correct: 3 },
                    { id: 69, question: "Which IoT device can be used for home automation?", options: ["Smart bulb", "Smart plug", "Smart thermostat", "All of the above"], correct: 4 },
                    { id: 70, question: "IoT devices generally operate with:", options: ["High power", "Low power", "Unlimited power", "Nuclear power"], correct: 2 },

                    { id: 71, question: "Which IoT protocol is application-layer based?", options: ["MQTT", "CoAP", "HTTP", "All of the above"], correct: 4 },
                    { id: 72, question: "Which is an IoT application in the retail sector?", options: ["Smart shelves", "Smart fitting rooms", "Inventory tracking", "All of the above"], correct: 4 },
                    { id: 73, question: "Which of the following helps in real-time IoT analytics?", options: ["Cloud computing", "Notepad", "CD-ROM", "Keyboard"], correct: 1 },
                    { id: 74, question: "Which of these is a unique identifier in IoT devices?", options: ["IP address", "Username", "Domain name", "E-mail ID"], correct: 1 },
                    { id: 75, question: "Which technology reduces IoT latency?", options: ["Edge computing", "Centralized computing", "Cloud storage only", "Manual processing"], correct: 1 },
                    { id: 76, question: "Which IoT application is widely used in automobiles?", options: ["Connected cars", "Word processors", "Photo editors", "Printers"], correct: 1 },
                    { id: 77, question: "Which IoT protocol is optimized for low-bandwidth devices?", options: ["MQTT", "SMTP", "POP3", "IMAP"], correct: 1 },
                    { id: 78, question: "Which of these is a risk in IoT device deployment?", options: ["Data privacy issues", "Text formatting errors", "File compression", "Image resizing"], correct: 1 },
                    { id: 79, question: "Which wireless technology is most commonly used in smart homes?", options: ["Zigbee", "DSL", "Token Ring", "ISDN"], correct: 1 },
                    { id: 80, question: "Which is an IoT application in agriculture?", options: ["Smart irrigation", "Video games", "Social networking", "E-mail"], correct: 1 },

                    { id: 81, question: "Which of these is a wearable IoT device for health monitoring?", options: ["Fitness band", "Mouse", "Keyboard", "Printer"], correct: 1 },
                    { id: 82, question: "Which of the following is a key benefit of IoT?", options: ["Automation", "Remote monitoring", "Cost reduction", "All of the above"], correct: 4 },
                    { id: 83, question: "Which type of IoT communication works in close proximity?", options: ["NFC", "Satellite", "Fiber optic", "DSL"], correct: 1 },
                    { id: 84, question: "Which IoT application is used in logistics?", options: ["Fleet tracking", "Word editing", "Spreadsheet", "Gaming"], correct: 1 },
                    { id: 85, question: "Which protocol is NOT used in IoT?", options: ["MQTT", "CoAP", "SMTP", "HTML"], correct: 4 },
                    { id: 86, question: "Which technology ensures unique identification of IoT devices?", options: ["RFID", "NLP", "OCR", "Compiler"], correct: 1 },
                    { id: 87, question: "Which IoT technology helps in predictive maintenance?", options: ["AI + IoT", "Gaming", "Photo editing", "Word processing"], correct: 1 },
                    { id: 88, question: "Which of the following is an IoT cloud provider?", options: ["Google Cloud IoT", "AWS IoT", "Azure IoT", "All of the above"], correct: 4 },
                    { id: 89, question: "Which IoT application helps reduce road accidents?", options: ["Smart traffic lights", "Smartwatches", "Fitness apps", "E-mail"], correct: 1 },
                    { id: 90, question: "Which communication technology is the backbone of future IoT?", options: ["5G", "Dial-up", "Coaxial cable", "ISDN"], correct: 1 },

                    { id: 91, question: "Which IoT device is used in smart farming?", options: ["Soil moisture sensor", "Keyboard", "Mouse", "Monitor"], correct: 1 },
                    { id: 92, question: "What does IPv6 offer for IoT?", options: ["More IP addresses", "Less IP addresses", "No addresses", "Only private addresses"], correct: 1 },
                    { id: 93, question: "Which IoT application is in the medical field?", options: ["Remote patient monitoring", "Gaming", "Cooking", "Photo editing"], correct: 1 },
                    { id: 94, question: "Which is an example of IoT in energy sector?", options: ["Smart meters", "Printers", "Word processors", "Scanners"], correct: 1 },
                    { id: 95, question: "Which IoT application belongs to transportation?", options: ["Connected vehicles", "Online chatting", "E-books", "Spreadsheet"], correct: 1 },
                    { id: 96, question: "Which of the following is a smart wearable?", options: ["Apple Watch", "CD-ROM", "Floppy disk", "Keyboard"], correct: 1 },
                    { id: 97, question: "Which of the following is an IoT security solution?", options: ["End-to-end encryption", "Firewalls", "Access control", "All of the above"], correct: 4 },
                    { id: 98, question: "Which is a smart healthcare IoT device?", options: ["Smart pill dispenser", "DVD drive", "Photocopier", "Printer"], correct: 1 },
                    { id: 99, question: "Which of the following is a smart wearable IoT gadget?", options: ["Google Glass", "Printer", "Scanner", "Monitor"], correct: 1 },
                    { id: 100, question: "Which IoT technology supports low-power wide-area networking?", options: ["LoRaWAN", "Token Ring", "Ethernet", "DSL"], correct: 1 },
                    { id: 101, question: "Which of the following is NOT a characteristic of IoT devices?", options: ["Low power", "Internet connectivity", "Data sensing", "High manual operation"], correct: 4 },
                    { id: 102, question: "Which IoT protocol is designed for constrained devices and networks?", options: ["HTTP", "CoAP", "FTP", "SMTP"], correct: 2 },
                    { id: 103, question: "Which IoT application is related to healthcare?", options: ["Remote surgery", "Movie streaming", "Photo editing", "Gaming"], correct: 1 },
                    { id: 104, question: "Which of these is an IoT platform by Microsoft?", options: ["Azure IoT Hub", "AWS IoT Core", "Google Cloud IoT", "IBM Watson IoT"], correct: 1 },
                    { id: 105, question: "Which IoT device is used in smart homes?", options: ["Smart thermostat", "Printer", "Scanner", "Photocopier"], correct: 1 },
                    { id: 106, question: "Which technology enables machine-to-machine (M2M) communication?", options: ["IoT", "LAN", "Email", "SMS"], correct: 1 },
                    { id: 107, question: "Which IoT layer focuses on sensing the environment?", options: ["Application Layer", "Perception Layer", "Network Layer", "Business Layer"], correct: 2 },
                    { id: 108, question: "Which IoT application helps reduce pollution?", options: ["Air quality monitoring", "Gaming apps", "Spreadsheets", "Typing tutor"], correct: 1 },
                    { id: 109, question: "Which of the following is an IoT protocol for device communication?", options: ["Zigbee", "XHTML", "CSS", "SMTP"], correct: 1 },
                    { id: 110, question: "Which technology is essential for real-time IoT applications?", options: ["5G", "Dial-up", "ISDN", "Cable TV"], correct: 1 },

                    { id: 111, question: "Which IoT application is used in hospitals?", options: ["Remote patient monitoring", "Photo editing", "Typing software", "Games"], correct: 1 },
                    { id: 112, question: "Which of these is an IoT-enabled transportation system?", options: ["Smart traffic management", "Smart irrigation", "Smart lighting", "Smart classroom"], correct: 1 },
                    { id: 113, question: "Which of these is a key feature of IoT?", options: ["Interconnectivity", "Isolation", "Manual operation", "Disconnection"], correct: 1 },
                    { id: 114, question: "Which IoT device is used in smart agriculture?", options: ["Soil sensors", "Mouse", "Keyboard", "Printer"], correct: 1 },
                    { id: 115, question: "Which protocol is widely used for IoT device messaging?", options: ["MQTT", "POP3", "IMAP", "FTP"], correct: 1 },
                    { id: 116, question: "Which of the following is NOT an IoT architecture layer?", options: ["Perception", "Network", "Application", "Presentation"], correct: 4 },
                    { id: 117, question: "Which IoT technology is used for contactless payments?", options: ["NFC", "SMTP", "POP3", "Ethernet"], correct: 1 },
                    { id: 118, question: "Which IoT component is responsible for taking action?", options: ["Sensor", "Actuator", "Router", "Database"], correct: 2 },
                    { id: 119, question: "Which IoT application is used in farming?", options: ["Smart irrigation", "Social media", "E-mail", "Games"], correct: 1 },
                    { id: 120, question: "Which IoT technology supports short-range wireless communication?", options: ["Bluetooth", "DSL", "ISDN", "Coaxial cable"], correct: 1 },

                    { id: 121, question: "Which of the following is an IoT application in healthcare?", options: ["Wearable heart monitor", "File compression tool", "Photo editor", "Scanner"], correct: 1 },
                    { id: 122, question: "Which IoT feature allows data analysis at device-level?", options: ["Edge computing", "Cloud-only computing", "Manual processing", "Batch processing"], correct: 1 },
                    { id: 123, question: "Which is an IoT platform by IBM?", options: ["Watson IoT", "Azure IoT", "AWS IoT", "Google IoT"], correct: 1 },
                    { id: 124, question: "Which IoT application is used in energy?", options: ["Smart meters", "Smart cars", "Smart classrooms", "Smart cameras"], correct: 1 },
                    { id: 125, question: "Which IoT protocol is based on request/response model?", options: ["HTTP", "MQTT", "SMTP", "IMAP"], correct: 1 },
                    { id: 126, question: "Which IoT component enables connectivity?", options: ["Router", "Sensor", "Database", "Actuator"], correct: 1 },
                    { id: 127, question: "Which IoT technology provides wide coverage and low power?", options: ["LoRaWAN", "Ethernet", "Token Ring", "ISDN"], correct: 1 },
                    { id: 128, question: "Which IoT application is used in smart homes?", options: ["Smart lighting", "Smart printer", "Smart keyboard", "Smart projector"], correct: 1 },
                    { id: 129, question: "Which of these is an IoT communication model?", options: ["Device-to-device", "Device-to-cloud", "Device-to-gateway", "All of the above"], correct: 4 },
                    { id: 130, question: "Which IoT technology ensures scalability?", options: ["Cloud computing", "CRT displays", "Floppy disks", "Punch cards"], correct: 1 },

                    { id: 131, question: "Which IoT application is used in security?", options: ["Smart surveillance cameras", "Word processors", "Printers", "Keyboards"], correct: 1 },
                    { id: 132, question: "Which IoT feature allows devices to operate without human intervention?", options: ["Automation", "Manual input", "Isolation", "Batch processing"], correct: 1 },
                    { id: 133, question: "Which IoT communication technology is best for wearable devices?", options: ["Bluetooth Low Energy", "Ethernet", "DSL", "Satellite"], correct: 1 },
                    { id: 134, question: "Which IoT device is used in logistics?", options: ["GPS trackers", "Scanners", "Printers", "Projectors"], correct: 1 },
                    { id: 135, question: "Which IoT application is related to smart cities?", options: ["Waste management", "Video streaming", "Social networking", "Gaming"], correct: 1 },
                    { id: 136, question: "Which IoT component is responsible for sensing data?", options: ["Sensor", "Actuator", "Gateway", "Database"], correct: 1 },
                    { id: 137, question: "Which IoT protocol is lightweight and suitable for messaging?", options: ["MQTT", "SMTP", "FTP", "POP3"], correct: 1 },
                    { id: 138, question: "Which IoT application is used in homes?", options: ["Smart locks", "Printers", "CD-ROM", "Scanners"], correct: 1 },
                    { id: 139, question: "Which IoT application is used in automobiles?", options: ["Connected cars", "Gaming consoles", "Photo editors", "Spreadsheets"], correct: 1 },
                    { id: 140, question: "Which IoT technology ensures device identification?", options: ["RFID", "OCR", "Compiler", "Debugger"], correct: 1 },

                    { id: 141, question: "Which of the following is an IoT cloud service?", options: ["Google Cloud IoT", "Azure IoT", "AWS IoT", "All of the above"], correct: 4 },
                    { id: 142, question: "Which IoT application belongs to industrial IoT?", options: ["Predictive maintenance", "Gaming apps", "Music apps", "Photo editors"], correct: 1 },
                    { id: 143, question: "Which IoT device is used in fitness?", options: ["Smartwatch", "Printer", "Scanner", "Keyboard"], correct: 1 },
                    { id: 144, question: "Which IoT technology is widely used in contactless cards?", options: ["NFC", "Ethernet", "DSL", "Coaxial cable"], correct: 1 },
                    { id: 145, question: "Which IoT feature enables devices to communicate directly?", options: ["M2M communication", "Isolation", "Offline processing", "Batch processing"], correct: 1 },
                    { id: 146, question: "Which IoT application is used in agriculture?", options: ["Crop monitoring", "Photo editing", "Word processing", "Gaming"], correct: 1 },
                    { id: 147, question: "Which IoT protocol works on the publish-subscribe model?", options: ["MQTT", "HTTP", "FTP", "SMTP"], correct: 1 },
                    { id: 148, question: "Which IoT device is used in smart homes?", options: ["Smart speakers", "Floppy disks", "Printers", "Scanners"], correct: 1 },
                    { id: 149, question: "Which IoT application is used in waste management?", options: ["Smart bins", "Word processors", "Gaming consoles", "Scanners"], correct: 1 },
                    { id: 150, question: "Which IoT feature ensures unique addressing?", options: ["IPv6", "IPv4 only", "Domain names", "MAC only"], correct: 1 },

                    { id: 151, question: "Which IoT application is in transportation?", options: ["Fleet tracking", "Video editing", "Word processing", "Photo scanning"], correct: 1 },
                    { id: 152, question: "Which IoT technology helps in large-scale device deployment?", options: ["Cloud computing", "CRT monitors", "Floppy disks", "Punch cards"], correct: 1 },
                    { id: 153, question: "Which IoT device is used for smart healthcare?", options: ["Smart insulin pumps", "Printers", "Scanners", "Typewriters"], correct: 1 },
                    { id: 154, question: "Which IoT application is related to home automation?", options: ["Smart appliances", "Gaming consoles", "E-mail apps", "CD-ROM"], correct: 1 },
                    { id: 155, question: "Which IoT technology supports ultra-low power consumption?", options: ["Bluetooth Low Energy", "Ethernet", "Token Ring", "DSL"], correct: 1 },
                    { id: 156, question: "Which IoT application helps monitor climate?", options: ["Weather sensors", "Photo editors", "Music players", "Word processors"], correct: 1 },
                    { id: 157, question: "Which IoT device is used in tracking pets?", options: ["GPS collars", "Scanners", "Monitors", "Keyboards"], correct: 1 },
                    { id: 158, question: "Which IoT application belongs to retail?", options: ["Inventory tracking", "Gaming", "Typing", "Photo editing"], correct: 1 },
                    { id: 159, question: "Which IoT feature reduces human intervention?", options: ["Automation", "Manual processing", "Offline storage", "Batch processing"], correct: 1 },
                    { id: 160, question: "Which IoT device is used in smart security systems?", options: ["Smart cameras", "Printers", "Scanners", "Keyboards"], correct: 1 },
                    { id: 161, question: "Which IoT protocol is best for lightweight messaging?", options: ["MQTT", "SMTP", "FTP", "POP3"], correct: 1 },
                    { id: 162, question: "Which IoT application belongs to agriculture?", options: ["Soil health monitoring", "Movie streaming", "Gaming", "Social media"], correct: 1 },
                    { id: 163, question: "Which IoT device is used for home automation?", options: ["Smart door locks", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 164, question: "Which technology enhances IoT with intelligence?", options: ["Artificial Intelligence", "Floppy disks", "Typewriters", "Manual input"], correct: 1 },
                    { id: 165, question: "Which IoT application is used in healthcare?", options: ["Wearable ECG monitor", "Gaming consoles", "Printers", "Scanners"], correct: 1 },
                    { id: 166, question: "Which IoT protocol works in request/response model?", options: ["HTTP", "MQTT", "SMTP", "IMAP"], correct: 1 },
                    { id: 167, question: "Which IoT application is in transportation?", options: ["Connected vehicles", "Spreadsheets", "Photo editing", "Typing software"], correct: 1 },
                    { id: 168, question: "Which IoT feature is enabled by IPv6?", options: ["Large address space", "Small memory", "File transfer", "Manual updates"], correct: 1 },
                    { id: 169, question: "Which IoT device is used for pet tracking?", options: ["GPS collars", "Scanners", "Monitors", "Routers"], correct: 1 },
                    { id: 170, question: "Which IoT application is used in smart cities?", options: ["Smart traffic lights", "Music apps", "E-mail", "Word processing"], correct: 1 },

                    { id: 171, question: "Which IoT protocol is secure for communication?", options: ["HTTPS", "FTP", "SMTP", "POP3"], correct: 1 },
                    { id: 172, question: "Which IoT device is used in fitness?", options: ["Smart band", "Printer", "Keyboard", "Scanner"], correct: 1 },
                    { id: 173, question: "Which IoT technology allows tap-and-pay?", options: ["NFC", "Ethernet", "DSL", "Coaxial cable"], correct: 1 },
                    { id: 174, question: "Which IoT application is in smart homes?", options: ["Smart lighting systems", "Gaming consoles", "File managers", "Printers"], correct: 1 },
                    { id: 175, question: "Which IoT technology is best for low-power long-range?", options: ["LoRaWAN", "Wi-Fi", "Bluetooth", "Ethernet"], correct: 1 },
                    { id: 176, question: "Which IoT device helps in remote patient monitoring?", options: ["Wearable health devices", "Scanners", "Routers", "Keyboards"], correct: 1 },
                    { id: 177, question: "Which IoT protocol is widely used for constrained devices?", options: ["CoAP", "SMTP", "Telnet", "FTP"], correct: 1 },
                    { id: 178, question: "Which IoT application is related to environment?", options: ["Air pollution sensors", "Word processors", "E-mail", "Video games"], correct: 1 },
                    { id: 179, question: "Which IoT feature reduces network delays?", options: ["Edge computing", "Centralized cloud only", "Manual processing", "Offline storage"], correct: 1 },
                    { id: 180, question: "Which IoT application is related to energy?", options: ["Smart grids", "CD-ROM", "Gaming consoles", "Scanners"], correct: 1 },

                    { id: 181, question: "Which IoT technology supports direct device-to-device communication?", options: ["Bluetooth", "DSL", "Ethernet", "ISDN"], correct: 1 },
                    { id: 182, question: "Which IoT device is used in logistics?", options: ["GPS trackers", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 183, question: "Which IoT application is part of Industry 4.0?", options: ["Predictive maintenance", "Gaming apps", "Word processors", "Photo editors"], correct: 1 },
                    { id: 184, question: "Which IoT protocol is based on publish/subscribe model?", options: ["MQTT", "HTTP", "FTP", "SMTP"], correct: 1 },
                    { id: 185, question: "Which IoT device is used for smart farming?", options: ["Soil moisture sensor", "Scanner", "Keyboard", "Monitor"], correct: 1 },
                    { id: 186, question: "Which IoT application belongs to retail?", options: ["Smart shelves", "Spreadsheet software", "Video players", "Photo editors"], correct: 1 },
                    { id: 187, question: "Which IoT feature enables automation?", options: ["Self-operating devices", "Manual processing", "Human-only control", "Offline files"], correct: 1 },
                    { id: 188, question: "Which IoT device is an example of smart wearables?", options: ["Apple Watch", "Printer", "Floppy disk", "Monitor"], correct: 1 },
                    { id: 189, question: "Which IoT application is used in public safety?", options: ["Smart surveillance", "Gaming", "Social networking", "Typing"], correct: 1 },
                    { id: 190, question: "Which IoT technology ensures device identification?", options: ["RFID", "SMTP", "OCR", "Compiler"], correct: 1 },

                    { id: 191, question: "Which IoT application belongs to waste management?", options: ["Smart bins", "CD-ROM", "Keyboard", "Spreadsheet"], correct: 1 },
                    { id: 192, question: "Which IoT technology provides short-range, low-energy communication?", options: ["Bluetooth Low Energy", "Ethernet", "DSL", "Satellite"], correct: 1 },
                    { id: 193, question: "Which IoT application is in healthcare?", options: ["Smart pill dispenser", "Gaming apps", "Video streaming", "Music players"], correct: 1 },
                    { id: 194, question: "Which IoT device is used in smart classrooms?", options: ["Smart boards", "Scanners", "Printers", "Floppy disks"], correct: 1 },
                    { id: 195, question: "Which IoT protocol is used for constrained RESTful environments?", options: ["CoAP", "SMTP", "POP3", "FTP"], correct: 1 },
                    { id: 196, question: "Which IoT application is in energy management?", options: ["Smart meters", "Word processors", "CD-ROM", "Gaming"], correct: 1 },
                    { id: 197, question: "Which IoT device is used in healthcare for vital tracking?", options: ["Smartwatch", "Monitor", "Keyboard", "Scanner"], correct: 1 },
                    { id: 198, question: "Which IoT application is in transportation?", options: ["Smart parking systems", "Typing tutors", "Video games", "Music apps"], correct: 1 },
                    { id: 199, question: "Which IoT feature ensures data security?", options: ["Encryption", "Open access", "No security", "Plain text storage"], correct: 1 },
                    { id: 200, question: "Which IoT technology reduces latency in real-time systems?", options: ["Edge computing", "Offline files", "Manual updates", "Batch processing"], correct: 1 },

                    { id: 201, question: "Which IoT device is used in smart homes?", options: ["Smart refrigerator", "Scanners", "Printers", "Monitors"], correct: 1 },
                    { id: 202, question: "Which IoT protocol is used for machine-to-machine communication?", options: ["MQTT", "POP3", "SMTP", "FTP"], correct: 1 },
                    { id: 203, question: "Which IoT application belongs to agriculture?", options: ["Crop monitoring", "Music players", "Gaming consoles", "Spreadsheets"], correct: 1 },
                    { id: 204, question: "Which IoT technology ensures unique identification of objects?", options: ["RFID", "SMTP", "Compiler", "OCR"], correct: 1 },
                    { id: 205, question: "Which IoT device is used in healthcare monitoring?", options: ["ECG sensors", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 206, question: "Which IoT application is used in logistics?", options: ["Fleet management", "CD-ROM", "Gaming apps", "Video editing"], correct: 1 },
                    { id: 207, question: "Which IoT technology is expected to drive IoT growth?", options: ["5G", "DSL", "ISDN", "Cable TV"], correct: 1 },
                    { id: 208, question: "Which IoT application is used in smart cities?", options: ["Smart waste management", "Word processors", "E-mail apps", "Printers"], correct: 1 },
                    { id: 209, question: "Which IoT feature provides automation?", options: ["Self-operation", "Manual updates", "Offline input", "Batch processing"], correct: 1 },
                    { id: 210, question: "Which IoT device is used for smart security?", options: ["Smart cameras", "Floppy disks", "Scanners", "Monitors"], correct: 1 },

                    { id: 211, question: "Which IoT protocol is optimized for constrained devices?", options: ["CoAP", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 212, question: "Which IoT application is in healthcare?", options: ["Remote patient monitoring", "Music streaming", "Typing tutors", "Photo editing"], correct: 1 },
                    { id: 213, question: "Which IoT device is wearable?", options: ["Fitness tracker", "Keyboard", "Printer", "Monitor"], correct: 1 },
                    { id: 214, question: "Which IoT application belongs to smart cities?", options: ["Smart street lighting", "Word editing", "Gaming", "Typing"], correct: 1 },
                    { id: 215, question: "Which IoT technology ensures better bandwidth and speed?", options: ["5G", "Dial-up", "ISDN", "Token Ring"], correct: 1 },
                    { id: 216, question: "Which IoT device is used in agriculture?", options: ["Drones", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 217, question: "Which IoT application is related to waste management?", options: ["Smart garbage bins", "Word processors", "Social networking", "Photo editing"], correct: 1 },
                    { id: 218, question: "Which IoT technology allows real-time processing?", options: ["Edge computing", "Offline updates", "Batch processing", "Manual input"], correct: 1 },
                    { id: 219, question: "Which IoT device is used in connected cars?", options: ["GPS system", "Scanners", "Printers", "Routers"], correct: 1 },
                    { id: 220, question: "Which IoT feature ensures devices can communicate over internet?", options: ["Connectivity", "Isolation", "Manual operation", "Offline files"], correct: 1 },
                    { id: 201, question: "Which IoT device is used in smart homes?", options: ["Smart refrigerator", "Scanners", "Printers", "Monitors"], correct: 1 },
                    { id: 202, question: "Which IoT protocol is used for machine-to-machine communication?", options: ["MQTT", "POP3", "SMTP", "FTP"], correct: 1 },
                    { id: 203, question: "Which IoT application belongs to agriculture?", options: ["Crop monitoring", "Music players", "Gaming consoles", "Spreadsheets"], correct: 1 },
                    { id: 204, question: "Which IoT technology ensures unique identification of objects?", options: ["RFID", "SMTP", "Compiler", "OCR"], correct: 1 },
                    { id: 205, question: "Which IoT device is used in healthcare monitoring?", options: ["ECG sensors", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 206, question: "Which IoT application is used in logistics?", options: ["Fleet management", "CD-ROM", "Gaming apps", "Video editing"], correct: 1 },
                    { id: 207, question: "Which IoT technology is expected to drive IoT growth?", options: ["5G", "DSL", "ISDN", "Cable TV"], correct: 1 },
                    { id: 208, question: "Which IoT application is used in smart cities?", options: ["Smart waste management", "Word processors", "E-mail apps", "Printers"], correct: 1 },
                    { id: 209, question: "Which IoT feature provides automation?", options: ["Self-operation", "Manual updates", "Offline input", "Batch processing"], correct: 1 },
                    { id: 210, question: "Which IoT device is used for smart security?", options: ["Smart cameras", "Floppy disks", "Scanners", "Monitors"], correct: 1 },

                    { id: 211, question: "Which IoT protocol is optimized for constrained devices?", options: ["CoAP", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 212, question: "Which IoT application is in healthcare?", options: ["Remote patient monitoring", "Music streaming", "Typing tutors", "Photo editing"], correct: 1 },
                    { id: 213, question: "Which IoT device is wearable?", options: ["Fitness tracker", "Keyboard", "Printer", "Monitor"], correct: 1 },
                    { id: 214, question: "Which IoT application belongs to smart cities?", options: ["Smart street lighting", "Word editing", "Gaming", "Typing"], correct: 1 },
                    { id: 215, question: "Which IoT technology ensures better bandwidth and speed?", options: ["5G", "Dial-up", "ISDN", "Token Ring"], correct: 1 },
                    { id: 216, question: "Which IoT device is used in agriculture?", options: ["Drones", "Printers", "Scanners", "Monitors"], correct: 1 },
                    { id: 217, question: "Which IoT application is related to waste management?", options: ["Smart garbage bins", "Word processors", "Social networking", "Photo editing"], correct: 1 },
                    { id: 218, question: "Which IoT technology allows real-time processing?", options: ["Edge computing", "Offline updates", "Batch processing", "Manual input"], correct: 1 },
                    { id: 219, question: "Which IoT device is used in connected cars?", options: ["GPS system", "Scanners", "Printers", "Routers"], correct: 1 },
                    { id: 220, question: "Which IoT feature ensures devices can communicate over internet?", options: ["Connectivity", "Isolation", "Manual operation", "Offline files"], correct: 1 },
                    { id: 221, question: "Which of the following is an example of an IoT wearable device?", options: ["Smartwatch", "Smart Fridge", "Smart TV", "Smart Car"], correct: 1 },
                    { id: 222, question: "Which IoT application is widely used in agriculture?", options: ["Soil moisture monitoring", "Smart TV apps", "Video conferencing", "Gaming"], correct: 1 },
                    { id: 223, question: "Which protocol is designed for constrained devices and networks in IoT?", options: ["CoAP", "FTP", "SMTP", "IMAP"], correct: 1 },
                    { id: 224, question: "Which of the following is a cloud platform for IoT?", options: ["AWS IoT Core", "Adobe Photoshop", "Google Docs", "MS Word"], correct: 1 },
                    { id: 225, question: "In IoT, which is the role of an actuator?", options: ["Takes action based on data", "Collects data", "Stores data", "Analyzes data"], correct: 1 },
                    { id: 226, question: "What does LPWAN stand for in IoT?", options: ["Low Power Wide Area Network", "Large Protocol Wide Access Network", "Low Profile Wireless Access Node", "Light Power Wireless Application Network"], correct: 1 },
                    { id: 227, question: "Which of the following is a major concern in IoT?", options: ["Security", "Cooking", "Gaming", "Entertainment"], correct: 1 },
                    { id: 228, question: "What type of sensors are used in smart home lighting systems?", options: ["Motion sensors", "Temperature sensors", "Pressure sensors", "Sound sensors"], correct: 1 },
                    { id: 229, question: "Which IoT protocol is most lightweight?", options: ["MQTT", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 230, question: "Which IoT communication technology is based on cellular networks?", options: ["NB-IoT", "Zigbee", "Bluetooth", "Wi-Fi"], correct: 1 },
                    { id: 231, question: "Which among these is a common IoT device in smart homes?", options: ["Smart thermostat", "Gaming console", "Printer", "Camera tripod"], correct: 1 },
                    { id: 232, question: "IoT devices often need to run on?", options: ["Low power", "High power", "Unlimited power", "Nuclear power"], correct: 1 },
                    { id: 233, question: "Which of the following is NOT an IoT communication protocol?", options: ["SMTP", "MQTT", "CoAP", "Zigbee"], correct: 1 },
                    { id: 234, question: "Which company developed Alexa for smart homes?", options: ["Amazon", "Microsoft", "Google", "Apple"], correct: 1 },
                    { id: 235, question: "Which of these is an industrial IoT application?", options: ["Predictive maintenance", "Playing music", "Gaming", "Video editing"], correct: 1 },
                    { id: 236, question: "Which of the following IoT communication methods works over very short ranges?", options: ["Bluetooth", "LoRaWAN", "NB-IoT", "Sigfox"], correct: 1 },
                    { id: 237, question: "IoT security often uses which encryption method?", options: ["AES", "JPEG", "MPEG", "MP3"], correct: 1 },
                    { id: 238, question: "Which is NOT a benefit of IoT?", options: ["Increased manual work", "Automation", "Efficiency", "Cost saving"], correct: 1 },
                    { id: 239, question: "IoT in healthcare can be used for?", options: ["Remote patient monitoring", "Watching movies", "Playing games", "Photo editing"], correct: 1 },
                    { id: 240, question: "Which technology is most useful for IoT device location tracking?", options: ["GPS", "Photoshop", "WordPress", "PowerPoint"], correct: 1 },

                    { id: 241, question: "Which is a standard for low-power wireless IoT networks?", options: ["Zigbee", "Ethernet", "HDMI", "USB"], correct: 1 },
                    { id: 242, question: "Which IoT communication method is suitable for smart meters?", options: ["NB-IoT", "Bluetooth", "USB", "VGA"], correct: 1 },
                    { id: 243, question: "IoT in smart cities is used for?", options: ["Traffic management", "Gaming", "Cooking", "Painting"], correct: 1 },
                    { id: 244, question: "Which technology is commonly used in wearable IoT devices?", options: ["Bluetooth", "Ethernet", "HDMI", "NFC"], correct: 1 },
                    { id: 245, question: "Which of these is a key IoT challenge?", options: ["Scalability", "Cooking", "Dancing", "Singing"], correct: 1 },
                    { id: 246, question: "Which is an IoT application in transportation?", options: ["Fleet tracking", "Music playback", "Video editing", "Text editing"], correct: 1 },
                    { id: 247, question: "Which of the following is an IoT cloud platform?", options: ["Google Cloud IoT", "Excel", "PowerPoint", "Word"], correct: 1 },
                    { id: 248, question: "Which type of sensor detects gas leakage in IoT systems?", options: ["Gas sensor", "Light sensor", "Sound sensor", "Motion sensor"], correct: 1 },
                    { id: 249, question: "Which of the following is NOT a wireless IoT communication technology?", options: ["Ethernet", "Zigbee", "LoRa", "Bluetooth"], correct: 1 },
                    { id: 250, question: "IoT device identity can be managed by?", options: ["Unique IDs", "Password only", "IPV4 only", "QR code only"], correct: 1 },

                    { id: 251, question: "Which IoT technology is designed for rural connectivity?", options: ["LoRaWAN", "Ethernet", "Bluetooth", "HDMI"], correct: 1 },
                    { id: 252, question: "IoT in retail is used for?", options: ["Smart shelves", "Cooking food", "Editing images", "Making videos"], correct: 1 },
                    { id: 253, question: "Which of the following is a security risk in IoT?", options: ["Data breach", "Fast charging", "Loud sound", "High brightness"], correct: 1 },
                    { id: 254, question: "Which network topology is most common in IoT?", options: ["Mesh", "Ring", "Bus", "Star"], correct: 1 },
                    { id: 255, question: "Which IoT protocol is most suitable for resource-constrained devices?", options: ["CoAP", "HTTP", "SMTP", "POP3"], correct: 1 },
                    { id: 256, question: "Which company developed Google Nest for smart homes?", options: ["Google", "Microsoft", "Apple", "IBM"], correct: 1 },
                    { id: 257, question: "Which of these is NOT an IoT enabling technology?", options: ["Blockchain", "5G", "Machine Learning", "Typewriter"], correct: 4 },
                    { id: 258, question: "Which IoT communication technology supports very long range?", options: ["LoRa", "Bluetooth", "Zigbee", "NFC"], correct: 1 },
                    { id: 259, question: "Which is an IoT application in energy management?", options: ["Smart grids", "Gaming consoles", "Video streaming", "Cooking"], correct: 1 },
                    { id: 260, question: "Which IoT technology is designed for battery-powered devices?", options: ["LPWAN", "Ethernet", "Fiber optics", "DSL"], correct: 1 },

                    { id: 261, question: "Which sensor is used in smart parking IoT systems?", options: ["Ultrasonic sensor", "Gas sensor", "Light sensor", "Sound sensor"], correct: 1 },
                    { id: 262, question: "Which IoT device is commonly used in agriculture?", options: ["Soil sensor", "Smart TV", "Printer", "Router"], correct: 1 },
                    { id: 263, question: "IoT devices often use which type of processors?", options: ["Microcontrollers", "Supercomputers", "Mainframes", "Quantum chips"], correct: 1 },
                    { id: 264, question: "Which IoT protocol is based on a publish-subscribe model?", options: ["MQTT", "HTTP", "SMTP", "IMAP"], correct: 1 },
                    { id: 265, question: "Which IoT standard focuses on interoperability?", options: ["OneM2M", "USB", "HDMI", "VGA"], correct: 1 },
                    { id: 266, question: "Which of the following is NOT an IoT device?", options: ["Smart Refrigerator", "Smartwatch", "Gaming Mouse", "Light bulb"], correct: 3 },
                    { id: 267, question: "Which layer of IoT architecture includes cloud services?", options: ["Application layer", "Perception layer", "Network layer", "Device layer"], correct: 1 },
                    { id: 268, question: "IoT applications in healthcare include?", options: ["Smart insulin pumps", "Text editing", "Photo filters", "Gaming"], correct: 1 },
                    { id: 269, question: "Which IoT device is used for home automation?", options: ["Smart thermostat", "Projector", "Scanner", "Keyboard"], correct: 1 },
                    { id: 270, question: "Which IoT protocol is commonly used for device discovery?", options: ["CoAP", "DNS-SD", "SMTP", "POP3"], correct: 2 },

                    { id: 271, question: "Which IoT application helps reduce energy consumption?", options: ["Smart lighting", "Gaming", "Cooking", "Painting"], correct: 1 },
                    { id: 272, question: "IoT in supply chain management helps in?", options: ["Tracking goods", "Editing videos", "Playing games", "Cooking food"], correct: 1 },
                    { id: 273, question: "Which of the following is a key feature of IoT devices?", options: ["Connectivity", "Unlimited storage", "High graphics", "Loud audio"], correct: 1 },
                    { id: 274, question: "Which IoT protocol is based on REST architecture?", options: ["CoAP", "MQTT", "SMTP", "POP3"], correct: 1 },
                    { id: 275, question: "Which company provides Azure IoT services?", options: ["Microsoft", "Apple", "Google", "Amazon"], correct: 1 },
                    { id: 276, question: "IoT applications in transportation include?", options: ["Traffic monitoring", "Photo editing", "Gaming", "Cooking"], correct: 1 },
                    { id: 277, question: "Which communication protocol is NOT used in IoT?", options: ["SMTP", "MQTT", "CoAP", "Zigbee"], correct: 1 },
                    { id: 278, question: "Which of the following IoT applications is used in homes?", options: ["Smart door locks", "Gaming console", "Printer", "Scanner"], correct: 1 },
                    { id: 279, question: "Which IoT standard is related to home automation?", options: ["Zigbee", "USB", "HDMI", "Ethernet"], correct: 1 },
                    { id: 280, question: "IoT sensors in smart farming can monitor?", options: ["Soil moisture", "Gaming score", "Movie ratings", "Cooking speed"], correct: 1 },

                    { id: 281, question: "Which wireless technology is commonly used in IoT healthcare devices?", options: ["Bluetooth Low Energy", "Ethernet", "HDMI", "VGA"], correct: 1 },
                    { id: 282, question: "IoT in disaster management is used for?", options: ["Early warning systems", "Gaming", "Cooking", "Photo editing"], correct: 1 },
                    { id: 283, question: "Which layer of IoT architecture contains sensors?", options: ["Perception layer", "Application layer", "Network layer", "Service layer"], correct: 1 },
                    { id: 284, question: "Which IoT device is commonly used in fitness tracking?", options: ["Smartwatch", "Smart oven", "Smart fridge", "Smart TV"], correct: 1 },
                    { id: 285, question: "Which IoT communication technology is best for long battery life?", options: ["LoRa", "Bluetooth", "Wi-Fi", "Ethernet"], correct: 1 },
                    { id: 286, question: "IoT in industrial automation helps with?", options: ["Predictive maintenance", "Cooking", "Painting", "Gaming"], correct: 1 },
                    { id: 287, question: "Which IoT security measure ensures data is not altered?", options: ["Integrity", "Confidentiality", "Availability", "Scalability"], correct: 1 },
                    { id: 288, question: "Which IoT application is related to smart energy?", options: ["Smart meters", "Gaming consoles", "Printers", "Speakers"], correct: 1 },
                    { id: 289, question: "Which protocol is often used for secure IoT communication?", options: ["TLS", "JPEG", "GIF", "MP3"], correct: 1 },
                    { id: 290, question: "IoT in education can be used for?", options: ["Smart classrooms", "Cooking", "Painting", "Gaming"], correct: 1 },

                    { id: 291, question: "Which IoT device helps control home lighting remotely?", options: ["Smart bulbs", "Projector", "Printer", "Scanner"], correct: 1 },
                    { id: 292, question: "Which IoT technology is used in contactless payments?", options: ["NFC", "Ethernet", "HDMI", "USB"], correct: 1 },
                    { id: 293, question: "Which of the following IoT applications is used in healthcare?", options: ["Wearable heart monitors", "Photo editing apps", "Video players", "Printers"], correct: 1 },
                    { id: 294, question: "Which IoT device is used in smart transportation?", options: ["GPS tracker", "Joystick", "Scanner", "Monitor"], correct: 1 },
                    { id: 295, question: "IoT devices often communicate via?", options: ["Wireless networks", "Paper letters", "DVDs", "USB only"], correct: 1 },
                    { id: 296, question: "Which is NOT a challenge of IoT?", options: ["Increased manual work", "Security", "Scalability", "Interoperability"], correct: 1 },
                    { id: 297, question: "IoT applications in smart homes include?", options: ["Energy management", "Cooking manually", "Gaming", "Painting"], correct: 1 },
                    { id: 298, question: "Which IoT standard is used for device-to-device communication?", options: ["Zigbee", "SMTP", "POP3", "HTTP"], correct: 1 },
                    { id: 299, question: "Which IoT technology supports massive device connectivity?", options: ["5G", "USB", "HDMI", "Ethernet"], correct: 1 },
                    { id: 300, question: "Which IoT device is used in agriculture for irrigation?", options: ["Smart sprinklers", "Projector", "Speaker", "Printer"], correct: 1 },
                    { id: 301, question: "Which protocol is lightweight and suitable for constrained IoT devices?", options: ["HTTP", "MQTT", "FTP", "SMTP"], correct: 2 },
                    { id: 302, question: "Which layer of IoT architecture ensures device-to-device communication?", options: ["Perception Layer", "Network Layer", "Application Layer", "Processing Layer"], correct: 2 },
                    { id: 303, question: "Which technology is used for location tracking in IoT?", options: ["GPS", "Bluetooth", "Zigbee", "LoRa"], correct: 1 },
                    { id: 304, question: "In IoT, CoAP stands for?", options: ["Constrained Application Protocol", "Control Access Protocol", "Connected Application Protocol", "Configuration Access Protocol"], correct: 1 },
                    { id: 305, question: "Which of the following is NOT an IoT communication protocol?", options: ["MQTT", "CoAP", "Zigbee", "MySQL"], correct: 4 },
                    { id: 306, question: "What does LPWAN stand for?", options: ["Low Power Wide Area Network", "Low Protocol Wide Area Network", "Long Protocol Wireless Area Network", "Low Precision Wireless Area Network"], correct: 1 },
                    { id: 307, question: "Which IoT protocol is based on the publish-subscribe model?", options: ["HTTP", "MQTT", "CoAP", "AMQP"], correct: 2 },
                    { id: 308, question: "IoT devices usually have constraints in?", options: ["Power", "Processing", "Memory", "All of the above"], correct: 4 },
                    { id: 309, question: "Which is the smallest unit of IoT system?", options: ["Gateway", "Device/Thing", "Cloud", "Application"], correct: 2 },
                    { id: 310, question: "Which of these is a key feature of IoT?", options: ["Connectivity", "Automation", "Sensing", "All of the above"], correct: 4 },
                    { id: 311, question: "Which cloud service is widely used in IoT?", options: ["AWS IoT Core", "Oracle VM", "MS Excel", "Apache Kafka"], correct: 1 },
                    { id: 312, question: "Which wireless technology is MOST energy efficient?", options: ["Wi-Fi", "Bluetooth Low Energy", "4G LTE", "Ethernet"], correct: 2 },
                    { id: 313, question: "Which security measure is most critical in IoT?", options: ["Authentication", "Encryption", "Access Control", "All of the above"], correct: 4 },
                    { id: 314, question: "IoT data analytics is used to?", options: ["Collect raw data", "Visualize and derive insights", "Build sensors", "Replace hardware"], correct: 2 },
                    { id: 315, question: "Which is an IoT middleware?", options: ["Node-RED", "Excel", "Photoshop", "Visual Studio"], correct: 1 },
                    { id: 316, question: "IoT gateways are responsible for?", options: ["Powering sensors", "Data aggregation and forwarding", "Manufacturing sensors", "Replacing actuators"], correct: 2 },
                    { id: 317, question: "Which of the following is an IoT operating system?", options: ["Contiki", "Windows 11", "Ubuntu Server", "RedHat Linux"], correct: 1 },
                    { id: 318, question: "Which is an example of an IoT application?", options: ["Smart Home", "Smart City", "Smart Healthcare", "All of the above"], correct: 4 },
                    { id: 319, question: "Which IoT communication protocol runs on UDP?", options: ["CoAP", "MQTT", "HTTP", "SMTP"], correct: 1 },
                    { id: 320, question: "Which of these technologies allows short-range IoT communication?", options: ["Bluetooth", "Wi-Fi", "Zigbee", "All of the above"], correct: 4 },
                    { id: 321, question: "Which IoT network is used for long-range, low-power communication?", options: ["Zigbee", "LoRaWAN", "Bluetooth", "Wi-Fi"], correct: 2 },
                    { id: 322, question: "IoT edge computing refers to?", options: ["Processing data near devices", "Processing only in cloud", "Only storing data", "Sending all raw data to server"], correct: 1 },
                    { id: 323, question: "Which of the following is an IoT platform?", options: ["Google Cloud IoT", "AWS IoT", "Azure IoT", "All of the above"], correct: 4 },
                    { id: 324, question: "Which of the following is used for IoT device discovery?", options: ["mDNS", "FTP", "SMTP", "ARP"], correct: 1 },
                    { id: 325, question: "Which is a challenge in IoT?", options: ["Interoperability", "Security", "Scalability", "All of the above"], correct: 4 },
                    { id: 326, question: "IoT actuators are used to?", options: ["Sense data", "Store data", "Perform actions", "Transmit data"], correct: 3 },
                    { id: 327, question: "Which type of sensor is used for temperature monitoring in IoT?", options: ["Accelerometer", "Thermistor", "Gyroscope", "Magnetometer"], correct: 2 },
                    { id: 328, question: "Which IoT protocol is widely used for smart homes?", options: ["Zigbee", "SMTP", "FTP", "Telnet"], correct: 1 },
                    { id: 329, question: "Which of the following is NOT a wireless IoT technology?", options: ["LoRa", "Zigbee", "Bluetooth", "USB"], correct: 4 },
                    { id: 330, question: "Which of the following is a healthcare IoT application?", options: ["Smartwatch monitoring", "Automated farming", "Traffic light control", "Smart parking"], correct: 1 },
                    { id: 331, question: "Which security method ensures only valid devices connect to IoT networks?", options: ["Authentication", "Encapsulation", "Virtualization", "Obfuscation"], correct: 1 },
                    { id: 332, question: "Which IoT protocol uses a REST-based model?", options: ["MQTT", "CoAP", "Zigbee", "FTP"], correct: 2 },
                    { id: 333, question: "Which IoT device is used in agriculture?", options: ["Soil moisture sensor", "Heart rate monitor", "Thermostat", "Camera"], correct: 1 },
                    { id: 334, question: "IoT-based traffic systems improve?", options: ["Traffic flow", "Safety", "Air quality", "All of the above"], correct: 4 },
                    { id: 335, question: "Which technology enables IoT devices to communicate directly without infrastructure?", options: ["Ad-hoc networks", "Wi-Fi", "Bluetooth", "Zigbee"], correct: 1 },
                    { id: 336, question: "IoT security threats include?", options: ["Data breach", "Botnet attack", "Device hijacking", "All of the above"], correct: 4 },
                    { id: 337, question: "Which protocol is mostly used in IoT for low-bandwidth communication?", options: ["MQTT", "SMTP", "POP3", "HTTP"], correct: 1 },
                    { id: 338, question: "IoT nodes usually consist of?", options: ["Sensors", "Microcontrollers", "Wireless modules", "All of the above"], correct: 4 },
                    { id: 339, question: "Which of these is an example of wearable IoT?", options: ["Fitbit", "Drone", "Smart TV", "Thermostat"], correct: 1 },
                    { id: 340, question: "IoT in industrial automation is called?", options: ["Industry 4.0", "Smart Factory", "IIoT", "All of the above"], correct: 4 },
                    { id: 341, question: "Which type of IoT network is Bluetooth used for?", options: ["PAN", "WAN", "LAN", "MAN"], correct: 1 },
                    { id: 342, question: "IoT gateways reduce?", options: ["Latency", "Bandwidth usage", "Cloud load", "All of the above"], correct: 4 },
                    { id: 343, question: "Which IoT standard is designed for smart home devices?", options: ["Matter", "SMTP", "Telnet", "IMAP"], correct: 1 },
                    { id: 344, question: "Which type of IP addressing is suitable for IoT?", options: ["IPv6", "IPv4", "MAC address only", "NAT only"], correct: 1 },
                    { id: 345, question: "Which cloud service model is best for IoT platforms?", options: ["IaaS", "PaaS", "SaaS", "All"], correct: 2 },
                    { id: 346, question: "Which IoT layer processes and analyzes data?", options: ["Application Layer", "Network Layer", "Perception Layer", "Processing Layer"], correct: 4 },
                    { id: 347, question: "Which is the biggest challenge in IoT security?", options: ["Scalability", "Device heterogeneity", "Data privacy", "Power efficiency"], correct: 3 },
                    { id: 348, question: "Which IoT system uses RFID tags?", options: ["Inventory management", "Weather monitoring", "Smart healthcare", "Wearables"], correct: 1 },
                    { id: 349, question: "Which of the following is a low-power IoT connectivity standard?", options: ["Z-Wave", "Ethernet", "DSL", "Cable"], correct: 1 },
                    { id: 350, question: "IoT fog computing is used for?", options: ["Edge-level processing", "Only cloud storage", "Only data sensing", "Remote hardware repair"], correct: 1 },
                    { id: 351, question: "Which of these is a benefit of IoT?", options: ["Automation", "Efficiency", "Real-time monitoring", "All of the above"], correct: 4 },
                    { id: 352, question: "IoT sensors convert?", options: ["Physical signals to digital data", "Digital data to images", "Cloud data to signals", "Code to applications"], correct: 1 },
                    { id: 353, question: "Which IoT protocol runs on top of TCP?", options: ["MQTT", "CoAP", "Zigbee", "Bluetooth"], correct: 1 },
                    { id: 354, question: "Which is a drawback of IoT?", options: ["Security risk", "High power demand", "Scalability issues", "All of the above"], correct: 4 },
                    { id: 355, question: "Which IoT device is used in smart parking?", options: ["Ultrasonic sensor", "Thermometer", "Heart sensor", "Barometer"], correct: 1 },
                    { id: 356, question: "Which IoT protocol is request/response based?", options: ["HTTP", "MQTT", "Zigbee", "LoRa"], correct: 1 },
                    { id: 357, question: "Which standard supports device interoperability in IoT?", options: ["IEEE 802.15.4", "SMTP", "HTTP", "POP3"], correct: 1 },
                    { id: 358, question: "IoT in agriculture is also called?", options: ["Smart Farming", "Smart City", "AgriNet", "Farm Cloud"], correct: 1 },
                    { id: 359, question: "Which protocol is widely used for IoT device messaging?", options: ["MQTT", "POP3", "SMTP", "IMAP"], correct: 1 },
                    { id: 360, question: "Which is a primary goal of IoT in healthcare?", options: ["Patient monitoring", "Weather monitoring", "Traffic control", "Energy saving"], correct: 1 },
                    { id: 361, question: "Which wireless technology is commonly used in smart meters?", options: ["Zigbee", "Bluetooth", "NFC", "Wi-Fi"], correct: 1 },
                    { id: 362, question: "Which IoT attack involves controlling devices remotely?", options: ["Botnet attack", "DoS attack", "Man-in-the-middle", "Phishing"], correct: 1 },
                    { id: 363, question: "IoT-based smart grids improve?", options: ["Power distribution", "Energy efficiency", "Demand forecasting", "All of the above"], correct: 4 },
                    { id: 364, question: "Which IoT device is commonly used in smart homes?", options: ["Smart thermostat", "Soil sensor", "Industrial PLC", "Satellite"], correct: 1 },
                    { id: 365, question: "Which IoT communication method is most reliable?", options: ["Wired Ethernet", "Bluetooth", "LoRa", "Zigbee"], correct: 1 },
                    { id: 366, question: "IoT predictive maintenance is used in?", options: ["Manufacturing", "Weather", "Healthcare", "Education"], correct: 1 },
                    { id: 367, question: "Which IoT component is used to execute physical changes?", options: ["Actuator", "Sensor", "Transmitter", "Gateway"], correct: 1 },
                    { id: 368, question: "Which IoT platform is open-source?", options: ["ThingsBoard", "AWS IoT", "Azure IoT", "Google IoT"], correct: 1 },
                    { id: 369, question: "Which type of data is generated by IoT devices?", options: ["Structured", "Unstructured", "Semi-structured", "All"], correct: 4 },
                    { id: 370, question: "Which IoT protocol is text-based?", options: ["HTTP", "MQTT", "Zigbee", "LoRa"], correct: 1 },
                    { id: 371, question: "Which is the main advantage of IPv6 in IoT?", options: ["Large address space", "Low energy", "More power", "High speed"], correct: 1 },
                    { id: 372, question: "Which IoT device is used in supply chain tracking?", options: ["RFID tag", "Thermometer", "Gyroscope", "Barometer"], correct: 1 },
                    { id: 373, question: "Which IoT standard is used for smart appliances?", options: ["Matter", "SMTP", "CoAP", "POP3"], correct: 1 },
                    { id: 374, question: "IoT interoperability issue arises due to?", options: ["Different protocols", "Different platforms", "Different devices", "All of the above"], correct: 4 },
                    { id: 375, question: "Which IoT security measure protects data transmission?", options: ["Encryption", "Obfuscation", "Compression", "Redundancy"], correct: 1 },
                    { id: 376, question: "IoT artificial intelligence is mainly used for?", options: ["Predictive analytics", "Basic sensing", "Wired communication", "Physical connectivity"], correct: 1 },
                    { id: 377, question: "Which IoT system is used in home automation?", options: ["Smart switches", "Soil sensor", "Wearables", "Smartwatch"], correct: 1 },
                    { id: 378, question: "IoT scalability challenge is related to?", options: ["Increasing number of devices", "Decreasing sensors", "Low bandwidth", "Less cloud storage"], correct: 1 },
                    { id: 379, question: "Which IoT concept enables machine-to-machine communication?", options: ["M2M", "HTTP", "SMTP", "POP3"], correct: 1 },
                    { id: 380, question: "Which is an example of industrial IoT?", options: ["Smart factory", "Smartwatch", "Smart home", "Fitness tracker"], correct: 1 },
                    { id: 380, question: "Which technology is primarily used in low-power wide-area networks (LPWAN) for IoT?", options: ["Zigbee", "LoRaWAN", "Bluetooth", "Wi-Fi"], correct: 2 },
                    { id: 381, question: "Which layer of IoT architecture handles data storage and analytics?", options: ["Perception layer", "Network layer", "Application layer", "Middleware layer"], correct: 4 },
                    { id: 382, question: "What is the function of RFID in IoT?", options: ["Data analytics", "Object identification", "Cloud computing", "Network routing"], correct: 2 },
                    { id: 383, question: "Which IoT protocol is lightweight and works on publish/subscribe?", options: ["HTTP", "CoAP", "MQTT", "AMQP"], correct: 3 },
                    { id: 384, question: "What does NB-IoT stand for?", options: ["New Broadband IoT", "Narrowband IoT", "Network-Based IoT", "Next-Bit IoT"], correct: 2 },
                    { id: 385, question: "Which is NOT a characteristic of IoT?", options: ["Interconnectivity", "Scalability", "Manual processing", "Intelligence"], correct: 3 },
                    { id: 386, question: "Which protocol is often used for IoT device discovery?", options: ["DNS-SD", "SMTP", "FTP", "POP3"], correct: 1 },
                    { id: 387, question: "Which of these is an IoT cloud platform?", options: ["AWS IoT", "Microsoft Azure IoT Hub", "Google Cloud IoT", "All of the above"], correct: 4 },
                    { id: 388, question: "What is the main purpose of IoT edge computing?", options: ["Perform computing at data centers", "Reduce latency by processing data near source", "Store data in cloud", "Increase power consumption"], correct: 2 },
                    { id: 389, question: "Which of the following is a short-range IoT communication technology?", options: ["LoRaWAN", "Bluetooth", "NB-IoT", "Sigfox"], correct: 2 },
                    { id: 390, question: "In IoT, what is an actuator?", options: ["A device that senses environment", "A device that processes data", "A device that performs actions", "A device that stores data"], correct: 3 },
                    { id: 391, question: "Which is a key security challenge in IoT?", options: ["Scalability", "Data confidentiality", "Interoperability", "Mobility"], correct: 2 },
                    { id: 392, question: "Which IoT protocol uses constrained devices with REST architecture?", options: ["HTTP", "CoAP", "MQTT", "AMQP"], correct: 2 },
                    { id: 393, question: "Which IoT layer ensures secure communication?", options: ["Perception layer", "Network layer", "Middleware layer", "Application layer"], correct: 2 },
                    { id: 394, question: "Which wireless technology supports mesh networking in IoT?", options: ["Bluetooth", "Zigbee", "Wi-Fi", "NB-IoT"], correct: 2 },
                    { id: 395, question: "What does M2M stand for in IoT?", options: ["Machine-to-Machine", "Middleware-to-Middleware", "Model-to-Model", "Micro-to-Macro"], correct: 1 },
                    { id: 396, question: "Which of these is NOT an IoT application?", options: ["Smart homes", "Autonomous vehicles", "Online video streaming", "Wearables"], correct: 3 },
                    { id: 397, question: "Which protocol is used for sending messages between IoT devices and brokers?", options: ["MQTT", "SMTP", "FTP", "SSH"], correct: 1 },
                    { id: 398, question: "Which IoT security approach ensures that devices communicate only with authorized servers?", options: ["Data integrity", "Authentication", "Encryption", "Hashing"], correct: 2 },
                    { id: 399, question: "What is the primary function of a gateway in IoT?", options: ["Connect IoT devices to internet", "Store IoT data", "Process IoT analytics", "Generate IoT power"], correct: 1 },
                    { id: 400, question: "Which IoT technology is designed for low power consumption and long battery life?", options: ["Bluetooth Classic", "Zigbee", "Wi-Fi", "Ethernet"], correct: 2 },
                    { id: 401, question: "Which standard is widely used for smart home IoT devices?", options: ["Zigbee", "Ethernet", "NB-IoT", "FTP"], correct: 1 },
                    { id: 402, question: "Which IoT network type uses unlicensed spectrum?", options: ["LoRaWAN", "NB-IoT", "LTE-M", "5G"], correct: 1 },
                    { id: 403, question: "Which IoT protocol works on UDP for constrained devices?", options: ["HTTP", "CoAP", "MQTT", "SMTP"], correct: 2 },
                    { id: 404, question: "Which of the following is NOT a sensor type?", options: ["Temperature sensor", "Humidity sensor", "Accelerometer", "Router"], correct: 4 },
                    { id: 405, question: "Which of these IoT devices is wearable?", options: ["Smartwatch", "Smart bulb", "Smart fridge", "Smart speaker"], correct: 1 },
                    { id: 406, question: "Which company developed Thread protocol for IoT?", options: ["Apple", "Google", "Intel", "Samsung"], correct: 2 },
                    { id: 407, question: "Which IoT technology is optimized for rural and remote connectivity?", options: ["Bluetooth", "LoRaWAN", "Wi-Fi", "Ethernet"], correct: 2 },
                    { id: 408, question: "Which IoT architecture layer interacts with end-users?", options: ["Perception", "Network", "Middleware", "Application"], correct: 4 },
                    { id: 409, question: "Which encryption standard is widely used in IoT for secure communication?", options: ["AES", "MD5", "SHA-1", "CRC"], correct: 1 },
                    { id: 410, question: "Which of these is a challenge in IoT deployment?", options: ["Scalability", "Security", "Interoperability", "All of the above"], correct: 4 },
                    { id: 411, question: "Which IoT standard is used for medical devices?", options: ["IEEE 802.15.6", "IEEE 802.11", "Zigbee", "Bluetooth Classic"], correct: 1 },
                    { id: 412, question: "Which protocol is considered more power-efficient for IoT?", options: ["MQTT", "HTTP", "FTP", "SMTP"], correct: 1 },
                    { id: 413, question: "What is the role of cloud computing in IoT?", options: ["Data storage and analytics", "Device manufacturing", "Network routing", "Energy management"], correct: 1 },
                    { id: 414, question: "Which IoT technology is a cellular standard?", options: ["NB-IoT", "LoRaWAN", "Zigbee", "Bluetooth"], correct: 1 },
                    { id: 415, question: "Which IoT concept refers to billions of devices connected worldwide?", options: ["Scalability", "Ubiquity", "Connectivity", "Massive IoT"], correct: 4 },
                    { id: 416, question: "Which IoT communication model is most energy-efficient?", options: ["Publish/Subscribe", "Request/Response", "Unicast", "Broadcast"], correct: 1 },
                    { id: 417, question: "Which IoT protocol is best suited for constrained networks?", options: ["MQTT", "HTTP", "SMTP", "POP3"], correct: 1 },
                    { id: 418, question: "Which is NOT an IoT protocol?", options: ["CoAP", "MQTT", "SMTP", "Zigbee"], correct: 3 },
                    { id: 419, question: "Which IoT device is primarily used in agriculture?", options: ["Soil moisture sensor", "Smartwatch", "Smart bulb", "Fitness tracker"], correct: 1 },
                    { id: 420, question: "Which layer in IoT is closest to physical devices?", options: ["Perception layer", "Network layer", "Middleware layer", "Application layer"], correct: 1 },
                    { id: 421, question: "Which IoT protocol is based on REST architecture?", options: ["HTTP", "CoAP", "MQTT", "AMQP"], correct: 2 },
                    { id: 422, question: "What is the main advantage of Zigbee in IoT?", options: ["High speed", "Low power consumption", "Long range", "High bandwidth"], correct: 2 },
                    { id: 423, question: "Which IoT technology is best for smart meters?", options: ["NB-IoT", "Bluetooth", "Wi-Fi", "Ethernet"], correct: 1 },
                    { id: 424, question: "Which IoT component ensures interaction with environment?", options: ["Sensor", "Gateway", "Cloud", "Router"], correct: 1 },
                    { id: 425, question: "Which IoT protocol is widely adopted in smart lighting?", options: ["Zigbee", "SMTP", "FTP", "DNS"], correct: 1 },
                    { id: 426, question: "Which company developed HomeKit for IoT?", options: ["Apple", "Google", "Amazon", "Microsoft"], correct: 1 },
                    { id: 427, question: "Which of these IoT devices is used in smart healthcare?", options: ["Heart-rate monitor", "Smart bulb", "Smart lock", "Smart fridge"], correct: 1 },
                    { id: 428, question: "Which of the following is a middleware platform in IoT?", options: ["Kaa", "CoAP", "Zigbee", "LoRaWAN"], correct: 1 },
                    { id: 429, question: "Which IoT security risk involves taking control of devices?", options: ["Data theft", "Device hijacking", "Interoperability", "Latency"], correct: 2 },
                    { id: 430, question: "Which IoT communication protocol runs over TCP/IP?", options: ["MQTT", "Zigbee", "LoRaWAN", "Bluetooth"], correct: 1 },
                    { id: 431, question: "Which IoT technology provides city-wide connectivity?", options: ["Zigbee", "Wi-Fi", "LoRaWAN", "Bluetooth"], correct: 3 },
                    { id: 432, question: "Which is the most important feature for wearable IoT devices?", options: ["Battery efficiency", "Data storage", "High speed", "Large screen"], correct: 1 },
                    { id: 433, question: "Which of the following is NOT a cloud provider for IoT?", options: ["AWS", "Azure", "Google Cloud", "Windows XP"], correct: 4 },
                    { id: 434, question: "Which protocol is used in IoT for constrained devices using low bandwidth?", options: ["MQTT", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 435, question: "Which IoT technology works on star topology?", options: ["LoRaWAN", "Bluetooth Mesh", "Zigbee Mesh", "Ethernet"], correct: 1 },
                    { id: 436, question: "Which IoT communication protocol is message-oriented?", options: ["MQTT", "SMTP", "FTP", "POP3"], correct: 1 },
                    { id: 437, question: "Which IoT sensor is used for motion detection?", options: ["Accelerometer", "Thermometer", "Hygrometer", "Barometer"], correct: 1 },
                    { id: 438, question: "Which IoT technology uses ISM bands for connectivity?", options: ["LoRaWAN", "NB-IoT", "Ethernet", "LTE"], correct: 1 },
                    { id: 439, question: "Which IoT standard is widely used for industrial automation?", options: ["OPC-UA", "SMTP", "HTTP", "POP3"], correct: 1 },
                    { id: 440, question: "Which of these is an example of smart city IoT application?", options: ["Smart parking", "Smartwatch", "Smart fridge", "Fitness tracker"], correct: 1 },
                    { id: 441, question: "Which IoT device is mainly used in smart farming?", options: ["Soil sensor", "Smart lock", "Smart bulb", "Smart speaker"], correct: 1 },
                    { id: 442, question: "Which layer of IoT ensures interoperability?", options: ["Application layer", "Network layer", "Middleware layer", "Perception layer"], correct: 3 },
                    { id: 443, question: "Which of the following ensures device identity in IoT?", options: ["Authentication", "Encryption", "Hashing", "Routing"], correct: 1 },
                    { id: 444, question: "Which IoT network technology has high bandwidth but high power usage?", options: ["Wi-Fi", "LoRaWAN", "Bluetooth", "Zigbee"], correct: 1 },
                    { id: 445, question: "Which IoT communication protocol is based on lightweight binary messaging?", options: ["MQTT-SN", "HTTP", "SMTP", "FTP"], correct: 1 },
                    { id: 446, question: "Which IoT application is used in healthcare monitoring?", options: ["Remote patient monitoring", "Smart parking", "Smart lighting", "Smart fridge"], correct: 1 },
                    { id: 447, question: "Which of the following is a low-cost IoT board?", options: ["Arduino", "Mainframe", "Supercomputer", "Server"], correct: 1 },
                    { id: 448, question: "Which IoT device collects atmospheric pressure?", options: ["Barometer", "Accelerometer", "Thermometer", "Hygrometer"], correct: 1 },
                    { id: 449, question: "Which IoT technology supports both IPv4 and IPv6?", options: ["6LoWPAN", "Zigbee", "Bluetooth", "LoRaWAN"], correct: 1 },
                    { id: 450, question: "Which IoT platform is open-source?", options: ["Kaa", "Azure IoT Hub", "AWS IoT", "Google Cloud IoT"], correct: 1 },
                    { id: 451, question: "Which of the following is a common IoT operating system?", options: ["Windows 10", "Contiki", "MS-DOS", "Ubuntu Server"], correct: 2 },
                    { id: 452, question: "IoT is primarily driven by advancements in?", options: ["AI", "Sensor technology", "Robotics", "5G"], correct: 2 },
                    { id: 453, question: "Which protocol is considered lightweight for IoT messaging?", options: ["HTTP", "FTP", "MQTT", "SMTP"], correct: 3 },
                    { id: 454, question: "Which of these is an IoT application in healthcare?", options: ["Smart Thermostat", "Wearable ECG monitor", "Smart TV", "E-learning"], correct: 2 },
                    { id: 455, question: "Which communication technology is best for short-range IoT?", options: ["Bluetooth Low Energy", "Satellite", "LoRaWAN", "5G"], correct: 1 },
                    { id: 456, question: "What does edge computing in IoT aim to reduce?", options: ["Latency", "Battery life", "Network size", "Protocol usage"], correct: 1 },
                    { id: 457, question: "Which cloud platform is widely used for IoT?", options: ["Dropbox", "AWS IoT Core", "WordPress", "Salesforce"], correct: 2 },
                    { id: 458, question: "Which IoT communication standard is designed for home automation?", options: ["Zigbee", "Ethernet", "HTTP", "SMTP"], correct: 1 },
                    { id: 459, question: "Which of the following is NOT an IoT layer?", options: ["Perception layer", "Network layer", "Application layer", "Compilation layer"], correct: 4 },
                    { id: 460, question: "The term 'Things' in IoT generally refers to?", options: ["Servers", "Connected devices", "Cloud platforms", "Networks"], correct: 2 },
                    { id: 461, question: "Which wireless technology is known as 'Machine to Machine' communication?", options: ["Bluetooth", "M2M", "Wi-Fi", "NFC"], correct: 2 },
                    { id: 462, question: "Which IoT protocol is based on publish/subscribe?", options: ["HTTP", "MQTT", "SMTP", "DNS"], correct: 2 },
                    { id: 463, question: "Which of these enables IoT security?", options: ["Strong encryption", "Open networks", "No authentication", "Shared passwords"], correct: 1 },
                    { id: 464, question: "Which IoT protocol works over UDP and is designed for resource-constrained devices?", options: ["CoAP", "SMTP", "FTP", "Telnet"], correct: 1 },
                    { id: 465, question: "What does NB-IoT stand for?", options: ["Network Based IoT", "Narrowband IoT", "New Blockchain IoT", "Network Basic IoT"], correct: 2 },
                    { id: 466, question: "Which of these is a major challenge in IoT devices?", options: ["Data storage", "Power consumption", "Display quality", "Video rendering"], correct: 2 },
                    { id: 467, question: "IoT devices are often constrained in?", options: ["Energy, processing, and memory", "Speed, graphics, and UI", "Networking, GUI, and audio", "Color, screen size, and resolution"], correct: 1 },
                    { id: 468, question: "Which of these is a cloud service for IoT?", options: ["Google Cloud IoT Core", "Adobe Photoshop", "Slack", "Zoom"], correct: 1 },
                    { id: 469, question: "Which frequency band is commonly used for IoT LPWAN?", options: ["2.4 GHz", "868/915 MHz", "5 GHz", "7 GHz"], correct: 2 },
                    { id: 470, question: "IoT analytics refers to?", options: ["Analyzing IoT data for insights", "Configuring IoT sensors", "Programming IoT boards", "Testing IoT batteries"], correct: 1 },
                    { id: 471, question: "Which is an example of wearable IoT?", options: ["Fitbit", "Smart bulb", "Smart refrigerator", "Smart thermostat"], correct: 1 },
                    { id: 472, question: "IoT is often referred to as the?", options: ["Internet of Servers", "Internet of Things", "Internet of Protocols", "Internet of Clouds"], correct: 2 },
                    { id: 473, question: "Which wireless protocol is used in smart homes?", options: ["Z-Wave", "SMTP", "FTP", "NTP"], correct: 1 },
                    { id: 474, question: "IoT is most effective when devices are?", options: ["Interconnected", "Isolated", "Unpowered", "Offline"], correct: 1 },
                    { id: 475, question: "Which is a security concern in IoT?", options: ["Unauthorized device access", "High-resolution display", "Color contrast", "Video streaming"], correct: 1 },
                    { id: 476, question: "IoT ecosystems include?", options: ["Devices, gateways, networks, and applications", "Only servers", "Only mobile apps", "Only cloud"], correct: 1 },
                    { id: 477, question: "Which IoT protocol is used for real-time streaming?", options: ["MQTT", "CoAP", "RTSP", "SMTP"], correct: 3 },
                    { id: 478, question: "IoT gateways are responsible for?", options: ["Connecting devices to cloud", "Storing offline movies", "Compiling code", "Debugging apps"], correct: 1 },
                    { id: 479, question: "Which IoT technology is best for smart agriculture?", options: ["LoRaWAN", "Bluetooth", "Wi-Fi", "HDMI"], correct: 1 },
                    { id: 480, question: "Which of these is an IoT healthcare device?", options: ["Blood glucose monitor", "Smart TV", "Gaming console", "Router"], correct: 1 },
                    { id: 481, question: "Which IoT protocol works on TCP/IP and supports request/response?", options: ["HTTP", "MQTT", "SMTP", "CoAP"], correct: 1 },
                    { id: 482, question: "IoT devices usually connect to cloud using?", options: ["Gateways", "Keyboards", "Printers", "Scanners"], correct: 1 },
                    { id: 483, question: "Which of the following is a benefit of IoT in transportation?", options: ["Traffic management", "Video editing", "Audio mixing", "Movie streaming"], correct: 1 },
                    { id: 484, question: "Which IoT protocol provides reliable lightweight communication?", options: ["MQTT", "FTP", "DNS", "Telnet"], correct: 1 },
                    { id: 485, question: "Which IoT use case belongs to smart cities?", options: ["Smart street lighting", "Photo editing", "Video calling", "File sharing"], correct: 1 },
                    { id: 486, question: "Which of the following is an IoT-enabled industrial system?", options: ["Smart factory", "Gaming console", "Television", "Printer"], correct: 1 },
                    { id: 487, question: "IoT devices can generate huge amounts of?", options: ["Data", "Games", "Music", "Movies"], correct: 1 },
                    { id: 488, question: "Which is a challenge in IoT networking?", options: ["Scalability", "Cooking", "Printing", "Typing"], correct: 1 },
                    { id: 489, question: "Which IoT protocol uses RESTful APIs?", options: ["CoAP", "SMTP", "FTP", "Telnet"], correct: 1 },
                    { id: 490, question: "Which of these is NOT an IoT protocol?", options: ["MQTT", "CoAP", "SMTP", "DNS"], correct: 3 },
                    { id: 491, question: "IoT applications in agriculture help in?", options: ["Precision farming", "Music playback", "Movie streaming", "Gaming"], correct: 1 },
                    { id: 492, question: "Which type of network is used by IoT devices?", options: ["PAN, LAN, WAN", "HDMI", "USB", "VGA"], correct: 1 },
                    { id: 493, question: "Which of the following is an IoT vulnerability?", options: ["Weak authentication", "High storage", "High graphics", "Large screen"], correct: 1 },
                    { id: 494, question: "IoT frameworks are used to?", options: ["Develop and manage IoT apps", "Play games", "Stream movies", "Write novels"], correct: 1 },
                    { id: 495, question: "Which IoT layer processes and analyzes collected data?", options: ["Application layer", "Network layer", "Perception layer", "Data layer"], correct: 1 },
                    { id: 496, question: "Which wireless standard is widely used in IoT wearable devices?", options: ["Bluetooth Low Energy", "HDMI", "VGA", "Ethernet"], correct: 1 },
                    { id: 497, question: "IoT in logistics helps in?", options: ["Real-time tracking", "Watching movies", "Gaming", "Emailing"], correct: 1 },
                    { id: 498, question: "Which IoT concept involves smart machines communicating?", options: ["M2M Communication", "Manual Communication", "Emailing", "Texting"], correct: 1 },
                    { id: 499, question: "IoT is closely related to which emerging technology?", options: ["Artificial Intelligence", "Typewriters", "Floppy disks", "CRT monitors"], correct: 1 },
                    { id: 500, question: "Which IoT application belongs to smart homes?", options: ["Smart thermostat", "Word processor", "Photo editor", "Antivirus"], correct: 1 }

                ]

            }
        }
}
export default IOT;