const computerNextwork = {

        color: "#F97316",
        subtopics: {
            "Types: PAN, LAN, MAN, WAN; topologies (bus, star, ring)": {
                color: "#F97316",
                questions: [
                    { id: 1, question: "Which type of network is used to connect devices within a small area such as a room?", options: ["LAN", "MAN", "PAN", "WAN"], correct: 3 },

                    { id: 2, question: "LAN stands for?", options: ["Local Area Network", "Large Area Network", "Limited Area Network", "Line Area Network"], correct: 1 },

                    { id: 3, question: "Which network spans across cities or large campuses?", options: ["LAN", "MAN", "WAN", "PAN"], correct: 2 },

                    { id: 4, question: "Which network is the largest in geographical coverage?", options: ["LAN", "PAN", "MAN", "WAN"], correct: 4 },

                    { id: 5, question: "Bluetooth is an example of which type of network?", options: ["LAN", "PAN", "MAN", "WAN"], correct: 3 },

                    { id: 6, question: "Which topology uses a central hub to connect all devices?", options: ["Bus", "Ring", "Star", "Mesh"], correct: 3 },

                    { id: 7, question: "In which topology does each device have exactly two neighbors?", options: ["Ring", "Bus", "Star", "Tree"], correct: 1 },

                    { id: 8, question: "Which network is typically used in an organization’s office building?", options: ["LAN", "MAN", "WAN", "PAN"], correct: 1 },

                    { id: 9, question: "Which topology has a single backbone cable connecting all nodes?", options: ["Ring", "Bus", "Star", "Mesh"], correct: 2 },

                    { id: 10, question: "Which network is most suitable for connecting across countries?", options: ["LAN", "PAN", "WAN", "MAN"], correct: 3 },

                    { id: 11, question: "What is a key disadvantage of bus topology?", options: ["Difficult to add new devices", "Single point of failure", "High cost", "No central hub"], correct: 2 },

                    { id: 12, question: "Which network is most cost-effective for home use?", options: ["PAN", "LAN", "MAN", "WAN"], correct: 1 },

                    { id: 13, question: "Which topology is more reliable because failure of one cable does not affect others?", options: ["Bus", "Ring", "Star", "Tree"], correct: 3 },

                    { id: 14, question: "Which topology requires a token to pass for data transmission?", options: ["Bus", "Ring", "Star", "Mesh"], correct: 2 },

                    { id: 15, question: "Which network is designed to connect devices across a metropolitan city?", options: ["WAN", "MAN", "LAN", "PAN"], correct: 2 },

                    { id: 16, question: "Which network is usually managed by a single person for personal devices?", options: ["WAN", "LAN", "PAN", "MAN"], correct: 3 },

                    { id: 17, question: "The Internet is an example of which type of network?", options: ["LAN", "WAN", "PAN", "MAN"], correct: 2 },

                    { id: 18, question: "Which topology has the easiest fault detection?", options: ["Ring", "Bus", "Star", "Mesh"], correct: 3 },

                    { id: 19, question: "Which topology is least expensive to implement?", options: ["Bus", "Star", "Ring", "Mesh"], correct: 1 },

                    { id: 20, question: "Which network type provides the fastest communication within a building?", options: ["WAN", "MAN", "LAN", "PAN"], correct: 3 },

                    { id: 21, question: "Which topology suffers if the central device fails?", options: ["Bus", "Star", "Ring", "Mesh"], correct: 2 },

                    { id: 22, question: "What is the main advantage of ring topology?", options: ["No collisions", "Easy to troubleshoot", "Low cost", "Independent of nodes"], correct: 1 },

                    { id: 23, question: "Which network type generally uses Ethernet cables?", options: ["LAN", "WAN", "PAN", "MAN"], correct: 1 },

                    { id: 24, question: "In bus topology, what happens if the backbone fails?", options: ["Network continues", "Only one node fails", "Entire network fails", "No effect"], correct: 3 },

                    { id: 25, question: "Which topology is commonly used in offices and schools?", options: ["Bus", "Star", "Ring", "Hybrid"], correct: 2 },

                    { id: 26, question: "Which type of network provides global connectivity?", options: ["PAN", "WAN", "LAN", "MAN"], correct: 2 },

                    { id: 27, question: "Which topology requires terminators at both ends?", options: ["Star", "Bus", "Ring", "Tree"], correct: 2 },

                    { id: 28, question: "Which network type covers a city-wide area?", options: ["LAN", "WAN", "MAN", "PAN"], correct: 3 },

                    { id: 29, question: "Which topology is highly secure as data passes through a central device?", options: ["Star", "Bus", "Ring", "Mesh"], correct: 1 },

                    { id: 30, question: "Which network type is limited to about 10 meters?", options: ["PAN", "WAN", "LAN", "MAN"], correct: 1 },

                    { id: 31, question: "Which topology is most affected by traffic load?", options: ["Ring", "Bus", "Star", "Tree"], correct: 2 },

                    { id: 32, question: "Which topology is easy to expand by adding new devices?", options: ["Star", "Bus", "Ring", "Mesh"], correct: 1 },

                    { id: 33, question: "Which network type is mostly wireless and personal?", options: ["WAN", "MAN", "PAN", "LAN"], correct: 3 },

                    { id: 34, question: "Which topology provides equal access time to all nodes?", options: ["Bus", "Star", "Ring", "Mesh"], correct: 3 },

                    { id: 35, question: "Which network uses routers for data transmission between countries?", options: ["LAN", "WAN", "PAN", "MAN"], correct: 2 },

                    { id: 36, question: "Which topology connects devices in a linear sequence?", options: ["Bus", "Ring", "Star", "Mesh"], correct: 1 },

                    { id: 37, question: "Which topology requires more cable length than bus topology?", options: ["Star", "Ring", "Tree", "Hybrid"], correct: 1 },

                    { id: 38, question: "Which network provides coverage for a university campus?", options: ["LAN", "WAN", "PAN", "MAN"], correct: 4 },

                    { id: 39, question: "Which topology requires token passing protocol?", options: ["Star", "Bus", "Ring", "Tree"], correct: 3 },

                    { id: 40, question: "Which network type is used in a single household?", options: ["WAN", "PAN", "MAN", "LAN"], correct: 2 },

                    { id: 41, question: "Which topology ensures high fault tolerance?", options: ["Star", "Ring", "Mesh", "Bus"], correct: 3 },

                    { id: 42, question: "Which network type connects small offices?", options: ["PAN", "WAN", "LAN", "MAN"], correct: 3 },

                    { id: 43, question: "Which topology uses a dedicated cable for each node to the hub?", options: ["Ring", "Bus", "Star", "Tree"], correct: 3 },

                    { id: 44, question: "Which topology is not suitable for large networks?", options: ["Ring", "Star", "Bus", "Mesh"], correct: 3 },

                    { id: 45, question: "Which network requires high bandwidth and speed within buildings?", options: ["WAN", "MAN", "LAN", "PAN"], correct: 3 },

                    { id: 46, question: "Which topology is difficult to configure and maintain?", options: ["Bus", "Star", "Mesh", "Ring"], correct: 3 },

                    { id: 47, question: "Which network type is the most private and secure?", options: ["LAN", "MAN", "WAN", "PAN"], correct: 4 },

                    { id: 48, question: "Which topology requires central coordination?", options: ["Star", "Bus", "Ring", "Mesh"], correct: 1 },

                    { id: 49, question: "Which network type generally has the lowest latency?", options: ["WAN", "LAN", "MAN", "PAN"], correct: 2 },

                    { id: 50, question: "Which topology can connect both linear and star networks?", options: ["Tree", "Ring", "Bus", "Mesh"], correct: 1 }
                ],
            },
            "OSI and TCP/IP model idea; what each layer does (simple mapping)": {
                color: "#10B981",
                questions: [
                    { id: 1, question: "How many layers are there in the OSI model?", options: ["5", "6", "7", "4"], correct: 3 },
                    { id: 2, question: "Which OSI layer is responsible for logical addressing and routing?", options: ["Transport", "Network", "Data Link", "Session"], correct: 2 },
                    { id: 3, question: "Which layer of the OSI model ensures error-free delivery of data?", options: ["Transport", "Network", "Session", "Physical"], correct: 1 },
                    { id: 4, question: "Which layer of OSI is responsible for data encryption and compression?", options: ["Application", "Presentation", "Session", "Transport"], correct: 2 },
                    { id: 5, question: "Which OSI layer breaks large messages into smaller segments?", options: ["Application", "Transport", "Network", "Data Link"], correct: 2 },
                    { id: 6, question: "Which OSI layer deals with bit-level transmission?", options: ["Data Link", "Network", "Physical", "Transport"], correct: 3 },
                    { id: 7, question: "Which layer of OSI establishes, manages, and terminates sessions?", options: ["Transport", "Session", "Network", "Application"], correct: 2 },
                    { id: 8, question: "Which OSI layer converts data into signals for transmission?", options: ["Physical", "Presentation", "Transport", "Session"], correct: 1 },
                    { id: 9, question: "TCP/IP has how many layers?", options: ["3", "4", "5", "7"], correct: 2 },
                    { id: 10, question: "Which TCP/IP layer corresponds to the OSI Application, Presentation, and Session layers?", options: ["Application", "Transport", "Internet", "Network Access"], correct: 1 },
                    { id: 11, question: "In TCP/IP, which layer ensures process-to-process delivery?", options: ["Transport", "Application", "Internet", "Network Access"], correct: 1 },
                    { id: 12, question: "In TCP/IP, which layer is responsible for routing packets?", options: ["Internet", "Transport", "Application", "Physical"], correct: 1 },
                    { id: 13, question: "The Data Link layer of OSI maps to which TCP/IP layer?", options: ["Application", "Internet", "Network Access", "Transport"], correct: 3 },
                    { id: 14, question: "Which OSI layer uses IP addresses for communication?", options: ["Transport", "Network", "Data Link", "Application"], correct: 2 },
                    { id: 15, question: "Which OSI layer uses MAC addresses?", options: ["Application", "Network", "Data Link", "Transport"], correct: 3 },
                    { id: 16, question: "Which OSI layer ensures reliable data delivery using acknowledgment?", options: ["Transport", "Network", "Session", "Presentation"], correct: 1 },
                    { id: 17, question: "Which OSI layer provides services like email, file transfer, and web browsing?", options: ["Transport", "Application", "Network", "Session"], correct: 2 },
                    { id: 18, question: "The function of error detection and correction belongs to which OSI layer?", options: ["Network", "Data Link", "Transport", "Physical"], correct: 2 },
                    { id: 19, question: "Which TCP/IP protocol is used at the Transport layer for reliable communication?", options: ["UDP", "TCP", "IP", "HTTP"], correct: 2 },
                    { id: 20, question: "Which TCP/IP protocol provides connectionless service at the Transport layer?", options: ["TCP", "UDP", "IP", "FTP"], correct: 2 },

                    { id: 21, question: "Which OSI layer converts data into a format suitable for the application?", options: ["Transport", "Session", "Presentation", "Application"], correct: 3 },
                    { id: 22, question: "Which TCP/IP layer handles hardware addressing?", options: ["Network Access", "Transport", "Application", "Internet"], correct: 1 },
                    { id: 23, question: "Which OSI layer is responsible for flow control?", options: ["Transport", "Network", "Data Link", "Session"], correct: 1 },
                    { id: 24, question: "Which OSI layer handles dialog control?", options: ["Session", "Presentation", "Transport", "Application"], correct: 1 },
                    { id: 25, question: "At which OSI layer do hubs and repeaters operate?", options: ["Data Link", "Network", "Physical", "Transport"], correct: 3 },
                    { id: 26, question: "Routers work at which OSI layer?", options: ["Transport", "Network", "Data Link", "Application"], correct: 2 },
                    { id: 27, question: "Switches primarily work at which OSI layer?", options: ["Data Link", "Physical", "Transport", "Network"], correct: 1 },
                    { id: 28, question: "Which TCP/IP layer uses HTTP, FTP, and SMTP?", options: ["Transport", "Application", "Internet", "Network Access"], correct: 2 },
                    { id: 29, question: "Which OSI layer converts electrical signals into bits?", options: ["Physical", "Transport", "Network", "Data Link"], correct: 1 },
                    { id: 30, question: "Which OSI layer is closest to the user?", options: ["Application", "Presentation", "Session", "Transport"], correct: 1 },

                    { id: 31, question: "In TCP/IP, IP is used at which layer?", options: ["Application", "Internet", "Transport", "Network Access"], correct: 2 },
                    { id: 32, question: "Which protocol is connectionless?", options: ["TCP", "UDP", "SMTP", "HTTP"], correct: 2 },
                    { id: 33, question: "Which protocol provides reliable communication?", options: ["TCP", "UDP", "IP", "ARP"], correct: 1 },
                    { id: 34, question: "Which layer in OSI is responsible for physical topology?", options: ["Network", "Data Link", "Physical", "Transport"], correct: 3 },
                    { id: 35, question: "At which OSI layer does the IP protocol work?", options: ["Data Link", "Transport", "Network", "Session"], correct: 3 },
                    { id: 36, question: "Which OSI layer handles end-to-end delivery?", options: ["Transport", "Network", "Data Link", "Physical"], correct: 1 },
                    { id: 37, question: "Which OSI layer ensures data is in readable format (JPEG, MP3, etc.)?", options: ["Presentation", "Application", "Session", "Transport"], correct: 1 },
                    { id: 38, question: "Which OSI layer assigns port numbers?", options: ["Network", "Transport", "Data Link", "Physical"], correct: 2 },
                    { id: 39, question: "Which OSI layer is responsible for multiplexing?", options: ["Transport", "Session", "Network", "Data Link"], correct: 1 },
                    { id: 40, question: "Which TCP/IP layer corresponds to OSI’s Network layer?", options: ["Application", "Transport", "Internet", "Network Access"], correct: 3 },

                    { id: 41, question: "Which OSI layer uses sockets for communication?", options: ["Application", "Network", "Transport", "Session"], correct: 3 },
                    { id: 42, question: "Which TCP/IP layer ensures host-to-host communication?", options: ["Application", "Internet", "Transport", "Network Access"], correct: 3 },
                    { id: 43, question: "Which OSI layer is responsible for character encoding?", options: ["Presentation", "Transport", "Session", "Application"], correct: 1 },
                    { id: 44, question: "Which OSI layer organizes data into frames?", options: ["Network", "Data Link", "Transport", "Application"], correct: 2 },
                    { id: 45, question: "Which OSI layer handles framing and error detection?", options: ["Data Link", "Network", "Transport", "Physical"], correct: 1 },
                    { id: 46, question: "Which TCP/IP layer handles ARP and Ethernet?", options: ["Internet", "Network Access", "Transport", "Application"], correct: 2 },
                    { id: 47, question: "Which OSI layer establishes synchronization between two systems?", options: ["Transport", "Session", "Presentation", "Application"], correct: 2 },
                    { id: 48, question: "Which OSI layer ensures data packets arrive in sequence?", options: ["Network", "Transport", "Session", "Data Link"], correct: 2 },
                    { id: 49, question: "In TCP/IP, which protocol translates domain names to IP addresses?", options: ["HTTP", "FTP", "DNS", "SMTP"], correct: 3 },
                    { id: 50, question: "Which OSI layer is concerned with path determination?", options: ["Data Link", "Session", "Network", "Transport"], correct: 3 },

                    { id: 51, question: "At which OSI layer does SSL/TLS work?", options: ["Transport", "Presentation", "Network", "Data Link"], correct: 2 },
                    { id: 52, question: "At which OSI layer does Ping (ICMP) work?", options: ["Transport", "Application", "Network", "Data Link"], correct: 3 },
                    { id: 53, question: "Which OSI layer uses sequence and acknowledgment numbers?", options: ["Transport", "Network", "Data Link", "Application"], correct: 1 },
                    { id: 54, question: "The physical transmission medium is defined at which OSI layer?", options: ["Physical", "Data Link", "Transport", "Network"], correct: 1 },
                    { id: 55, question: "The process of encapsulation happens in which model?", options: ["OSI", "TCP/IP", "Both", "None"], correct: 3 },
                    { id: 56, question: "Which OSI layer uses frames as data units?", options: ["Physical", "Data Link", "Network", "Transport"], correct: 2 },
                    { id: 57, question: "Which OSI layer uses packets as data units?", options: ["Transport", "Network", "Data Link", "Session"], correct: 2 },
                    { id: 58, question: "Which OSI layer uses segments as data units?", options: ["Transport", "Data Link", "Network", "Physical"], correct: 1 },
                    { id: 59, question: "Which OSI layer uses bits as data units?", options: ["Physical", "Data Link", "Network", "Transport"], correct: 1 },
                    { id: 60, question: "Which OSI layer uses data as data units?", options: ["Application", "Network", "Session", "Transport"], correct: 1 },

                    { id: 61, question: "Which TCP/IP protocol is used to transfer files?", options: ["SMTP", "FTP", "HTTP", "SNMP"], correct: 2 },
                    { id: 62, question: "Which TCP/IP protocol is used for email transfer?", options: ["SMTP", "HTTP", "DNS", "FTP"], correct: 1 },
                    { id: 63, question: "Which TCP/IP protocol is used for web browsing?", options: ["FTP", "HTTP", "SMTP", "SNMP"], correct: 2 },
                    { id: 64, question: "Which TCP/IP protocol is used for network management?", options: ["FTP", "HTTP", "SNMP", "SMTP"], correct: 3 },
                    { id: 65, question: "Which OSI layer is also called the end-user layer?", options: ["Session", "Presentation", "Application", "Transport"], correct: 3 },
                    { id: 66, question: "Which TCP/IP layer is also known as the Link layer?", options: ["Internet", "Transport", "Network Access", "Application"], correct: 3 },
                    { id: 67, question: "At which OSI layer do gateways operate?", options: ["Network", "Session", "Application", "Transport"], correct: 3 },
                    { id: 68, question: "Which OSI layer performs data translation between different formats?", options: ["Transport", "Session", "Application", "Presentation"], correct: 4 },
                    { id: 69, question: "Which OSI layer provides connection establishment?", options: ["Transport", "Session", "Network", "Data Link"], correct: 2 },
                    { id: 70, question: "Which TCP/IP protocol is used to fetch email from a server?", options: ["POP3/IMAP", "SMTP", "HTTP", "FTP"], correct: 1 },

                    { id: 71, question: "Which OSI layer provides services for file transfer and remote login?", options: ["Presentation", "Transport", "Application", "Session"], correct: 3 },
                    { id: 72, question: "Which OSI layer provides error notification?", options: ["Data Link", "Transport", "Network", "Physical"], correct: 2 },
                    { id: 73, question: "Which OSI layer is responsible for routing and congestion control?", options: ["Transport", "Network", "Data Link", "Session"], correct: 2 },
                    { id: 74, question: "Which TCP/IP protocol is responsible for remote terminal access?", options: ["SMTP", "Telnet", "FTP", "HTTP"], correct: 2 },
                    { id: 75, question: "Which OSI layer provides data integrity and sequencing?", options: ["Session", "Transport", "Network", "Data Link"], correct: 2 },
                    { id: 76, question: "Which OSI layer provides reliable process-to-process communication?", options: ["Network", "Data Link", "Transport", "Physical"], correct: 3 },
                    { id: 77, question: "At which OSI layer does a bridge work?", options: ["Physical", "Data Link", "Transport", "Network"], correct: 2 },
                    { id: 78, question: "Which OSI layer takes care of syntax and semantics of information?", options: ["Transport", "Presentation", "Application", "Session"], correct: 2 },
                    { id: 79, question: "Which OSI layer handles peer-to-peer communication?", options: ["Transport", "Network", "Session", "Data Link"], correct: 1 },
                    { id: 80, question: "Which OSI layer establishes, maintains, and terminates virtual circuits?", options: ["Session", "Transport", "Application", "Network"], correct: 2 }
                ],
            },
            "Protocols: IP, TCP/UDP, HTTP/HTTPS, FTP, SMTP/POP/IMAP, DNS, DHCP": {
                color: "#14B8A6",
                questions: [
                    { id: 1, question: "Which protocol is responsible for assigning IP addresses dynamically?", options: ["DNS", "DHCP", "FTP", "SMTP"], correct: 2 },
                    { id: 2, question: "Which protocol translates domain names to IP addresses?", options: ["FTP", "DHCP", "DNS", "HTTP"], correct: 3 },
                    { id: 3, question: "Which protocol is used to transfer files over the Internet?", options: ["SMTP", "FTP", "TCP", "POP"], correct: 2 },
                    { id: 4, question: "Which layer of TCP/IP model does IP work in?", options: ["Application", "Transport", "Internet", "Network Access"], correct: 3 },
                    { id: 5, question: "Which protocol provides reliable communication with acknowledgment?", options: ["TCP", "UDP", "IP", "FTP"], correct: 1 },
                    { id: 6, question: "Which protocol is connectionless and faster but less reliable?", options: ["TCP", "UDP", "HTTP", "SMTP"], correct: 2 },
                    { id: 7, question: "Which protocol is used for sending emails?", options: ["POP3", "IMAP", "SMTP", "FTP"], correct: 3 },
                    { id: 8, question: "Which protocol is used for retrieving emails from a mail server to a client?", options: ["SMTP", "DNS", "POP3", "DHCP"], correct: 3 },
                    { id: 9, question: "Which email protocol allows synchronization across multiple devices?", options: ["POP3", "IMAP", "SMTP", "FTP"], correct: 2 },
                    { id: 10, question: "Which protocol runs on port 80?", options: ["HTTPS", "HTTP", "FTP", "DNS"], correct: 2 },

                    { id: 11, question: "Which protocol runs on port 443?", options: ["HTTP", "FTP", "HTTPS", "SMTP"], correct: 3 },
                    { id: 12, question: "Which protocol is more secure than HTTP?", options: ["DNS", "HTTPS", "TCP", "UDP"], correct: 2 },
                    { id: 13, question: "Which protocol provides end-to-end communication between applications?", options: ["IP", "TCP", "DNS", "DHCP"], correct: 2 },
                    { id: 14, question: "Which protocol is responsible for routing packets?", options: ["TCP", "IP", "SMTP", "HTTP"], correct: 2 },
                    { id: 15, question: "Which protocol resolves hostnames to IP addresses?", options: ["DNS", "DHCP", "HTTP", "IMAP"], correct: 1 },
                    { id: 16, question: "Which protocol works with a request-response mechanism for web pages?", options: ["FTP", "HTTP", "SMTP", "DNS"], correct: 2 },
                    { id: 17, question: "Which protocol is commonly used for streaming video and audio?", options: ["TCP", "UDP", "SMTP", "FTP"], correct: 2 },
                    { id: 18, question: "Which protocol ensures error detection and correction?", options: ["UDP", "TCP", "HTTP", "DNS"], correct: 2 },
                    { id: 19, question: "Which protocol uses port 25?", options: ["SMTP", "POP3", "IMAP", "DNS"], correct: 1 },
                    { id: 20, question: "Which protocol uses port 110?", options: ["SMTP", "IMAP", "POP3", "FTP"], correct: 3 },

                    { id: 21, question: "Which protocol uses port 143?", options: ["IMAP", "SMTP", "POP3", "DNS"], correct: 1 },
                    { id: 22, question: "Which protocol uses port 21?", options: ["FTP", "DNS", "HTTP", "IMAP"], correct: 1 },
                    { id: 23, question: "Which protocol uses port 53?", options: ["DHCP", "FTP", "DNS", "SMTP"], correct: 3 },
                    { id: 24, question: "Which protocol uses port 67/68?", options: ["FTP", "SMTP", "DHCP", "HTTP"], correct: 3 },
                    { id: 25, question: "Which protocol is used when typing a website name into a browser?", options: ["DNS", "SMTP", "DHCP", "POP3"], correct: 1 },
                    { id: 26, question: "Which protocol is required for IP address lease?", options: ["TCP", "DHCP", "DNS", "FTP"], correct: 2 },
                    { id: 27, question: "Which protocol uses 3-way handshake?", options: ["UDP", "TCP", "SMTP", "FTP"], correct: 2 },
                    { id: 28, question: "Which protocol does not guarantee packet delivery?", options: ["TCP", "UDP", "IP", "DHCP"], correct: 2 },
                    { id: 29, question: "Which protocol is often used with VoIP?", options: ["TCP", "UDP", "FTP", "SMTP"], correct: 2 },
                    { id: 30, question: "Which protocol secures email transfer with encryption?", options: ["HTTPS", "SMTPS", "DNSSEC", "FTPS"], correct: 2 },

                    { id: 31, question: "Which protocol is the backbone of the Internet?", options: ["HTTP", "IP", "FTP", "SMTP"], correct: 2 },
                    { id: 32, question: "Which protocol ensures message delivery order?", options: ["UDP", "TCP", "IP", "FTP"], correct: 2 },
                    { id: 33, question: "Which protocol allows anonymous login?", options: ["HTTP", "SMTP", "FTP", "DHCP"], correct: 3 },
                    { id: 34, question: "Which protocol provides both static and dynamic addressing?", options: ["DNS", "DHCP", "FTP", "TCP"], correct: 2 },
                    { id: 35, question: "Which protocol is used for secure file transfer?", options: ["FTP", "SFTP", "SMTP", "POP"], correct: 2 },
                    { id: 36, question: "Which protocol is required for browsing websites?", options: ["FTP", "HTTP", "DHCP", "DNS"], correct: 2 },
                    { id: 37, question: "Which protocol is responsible for fragmentation of packets?", options: ["TCP", "IP", "DNS", "SMTP"], correct: 2 },
                    { id: 38, question: "Which protocol is stateless?", options: ["HTTP", "TCP", "SMTP", "IMAP"], correct: 1 },
                    { id: 39, question: "Which protocol maintains session state?", options: ["HTTP", "HTTPS", "TCP", "UDP"], correct: 3 },
                    { id: 40, question: "Which protocol is faster but unreliable?", options: ["TCP", "UDP", "HTTP", "SMTP"], correct: 2 },

                    { id: 41, question: "Which protocol is used to configure devices automatically?", options: ["FTP", "DHCP", "DNS", "SMTP"], correct: 2 },
                    { id: 42, question: "Which protocol is used for domain name resolution?", options: ["DNS", "SMTP", "IMAP", "FTP"], correct: 1 },
                    { id: 43, question: "Which protocol operates at the transport layer?", options: ["TCP/UDP", "IP", "DNS", "HTTP"], correct: 1 },
                    { id: 44, question: "Which protocol works at the application layer for email sending?", options: ["POP", "SMTP", "IMAP", "FTP"], correct: 2 },
                    { id: 45, question: "Which protocol allows remote login to retrieve files?", options: ["HTTP", "FTP", "SMTP", "DNS"], correct: 2 },
                    { id: 46, question: "Which protocol supports IPv4 addressing?", options: ["DNS", "IP", "TCP", "SMTP"], correct: 2 },
                    { id: 47, question: "Which protocol supports IPv6?", options: ["IP", "FTP", "DNS", "HTTP"], correct: 1 },
                    { id: 48, question: "Which protocol supports digital certificates?", options: ["HTTP", "HTTPS", "SMTP", "IMAP"], correct: 2 },
                    { id: 49, question: "Which protocol can prevent DNS spoofing?", options: ["DNSSEC", "DHCP", "FTP", "IMAP"], correct: 1 },
                    { id: 50, question: "Which protocol provides host-to-host delivery?", options: ["TCP", "IP", "DNS", "DHCP"], correct: 1 },

                    { id: 51, question: "Which protocol breaks data into packets?", options: ["IP", "DNS", "FTP", "SMTP"], correct: 1 },
                    { id: 52, question: "Which protocol checks error in data packets?", options: ["TCP", "UDP", "IP", "DHCP"], correct: 1 },
                    { id: 53, question: "Which protocol works without a connection setup?", options: ["TCP", "UDP", "SMTP", "FTP"], correct: 2 },
                    { id: 54, question: "Which protocol is suitable for DNS queries?", options: ["TCP", "UDP", "HTTP", "SMTP"], correct: 2 },
                    { id: 55, question: "Which protocol uses SSL/TLS for security?", options: ["HTTP", "HTTPS", "FTP", "DNS"], correct: 2 },
                    { id: 56, question: "Which protocol is used for secure email retrieval?", options: ["IMAPS/POP3S", "DNSSEC", "FTPS", "SMTPS"], correct: 1 },
                    { id: 57, question: "Which protocol is used for bulk file transfer?", options: ["FTP", "SMTP", "DHCP", "IMAP"], correct: 1 },
                    { id: 58, question: "Which protocol enables VoIP communication?", options: ["TCP", "UDP", "FTP", "SMTP"], correct: 2 },
                    { id: 59, question: "Which protocol allows multiple users to access email?", options: ["POP3", "IMAP", "SMTP", "DNS"], correct: 2 },
                    { id: 60, question: "Which protocol works on client-server architecture?", options: ["DNS", "SMTP", "HTTP", "All of these"], correct: 4 },

                    { id: 61, question: "Which protocol handles retransmission of lost packets?", options: ["TCP", "UDP", "IP", "DNS"], correct: 1 },
                    { id: 62, question: "Which protocol is best for real-time gaming?", options: ["TCP", "UDP", "HTTP", "SMTP"], correct: 2 },
                    { id: 63, question: "Which protocol is best for web browsing?", options: ["UDP", "TCP", "IP", "DNS"], correct: 2 },
                    { id: 64, question: "Which protocol secures DNS queries?", options: ["DNSSEC", "HTTPS", "FTPS", "DHCP"], correct: 1 },
                    { id: 65, question: "Which protocol allows transferring website files?", options: ["FTP", "SMTP", "DNS", "POP3"], correct: 1 },
                    { id: 66, question: "Which protocol uses User Datagram?", options: ["TCP", "UDP", "IP", "HTTP"], correct: 2 },
                    { id: 67, question: "Which protocol uses Segment?", options: ["UDP", "TCP", "IP", "DNS"], correct: 2 },
                    { id: 68, question: "Which protocol is faster for streaming?", options: ["TCP", "UDP", "FTP", "DNS"], correct: 2 },
                    { id: 69, question: "Which protocol ensures session establishment?", options: ["UDP", "TCP", "DHCP", "SMTP"], correct: 2 },
                    { id: 70, question: "Which protocol is used for assigning gateway addresses?", options: ["DNS", "DHCP", "FTP", "SMTP"], correct: 2 },

                    { id: 71, question: "Which protocol uses hierarchical naming?", options: ["DNS", "DHCP", "SMTP", "FTP"], correct: 1 },
                    { id: 72, question: "Which protocol is essential for IP communication?", options: ["DNS", "IP", "DHCP", "HTTP"], correct: 2 },
                    { id: 73, question: "Which protocol helps in browsing with HTTPS certificates?", options: ["DNS", "SSL/TLS", "DHCP", "IMAP"], correct: 2 },
                    { id: 74, question: "Which protocol is used for secure login while file transfer?", options: ["FTP", "SFTP", "SMTP", "DNS"], correct: 2 },
                    { id: 75, question: "Which protocol is faster but lacks error correction?", options: ["TCP", "UDP", "IP", "SMTP"], correct: 2 },
                    { id: 76, question: "Which protocol helps ISPs assign IP addresses?", options: ["DNS", "DHCP", "SMTP", "IMAP"], correct: 2 },
                    { id: 77, question: "Which protocol allows remote access to email?", options: ["IMAP", "POP3", "SMTP", "FTP"], correct: 1 },
                    { id: 78, question: "Which protocol manages IP to MAC mapping?", options: ["ARP", "DHCP", "DNS", "FTP"], correct: 1 },
                    { id: 79, question: "Which protocol is lightweight for communication?", options: ["TCP", "UDP", "IP", "SMTP"], correct: 2 },
                    { id: 80, question: "Which protocol supports encryption for website security?", options: ["HTTP", "HTTPS", "FTP", "DNS"], correct: 2 }
                ],
            },
            "IP addressing basics, URL/domain concepts, client–server": {
                color: "#0EA5E9",
                questions: [
                    { id: 1, question: "What does IP stand for in networking?", options: ["Internet Program", "Internal Protocol", "Internet Protocol", "Interface Program"], correct: 3 },
                    { id: 2, question: "How many bits are there in an IPv4 address?", options: ["32 bits", "64 bits", "128 bits", "16 bits"], correct: 1 },
                    { id: 3, question: "How many bits are there in an IPv6 address?", options: ["32 bits", "64 bits", "128 bits", "256 bits"], correct: 3 },
                    { id: 4, question: "Which of the following is a private IP address?", options: ["192.168.1.1", "8.8.8.8", "172.217.5.14", "1.1.1.1"], correct: 1 },
                    { id: 5, question: "Which class of IP addresses is used for multicast?", options: ["Class A", "Class B", "Class C", "Class D"], correct: 4 },
                    { id: 6, question: "What is the default subnet mask for a Class C IP?", options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], correct: 3 },
                    { id: 7, question: "What is the range of Class A IP addresses?", options: ["1.0.0.0 – 126.0.0.0", "128.0.0.0 – 191.255.0.0", "192.0.0.0 – 223.255.255.0", "224.0.0.0 – 239.255.255.255"], correct: 1 },
                    { id: 8, question: "Which protocol translates domain names into IP addresses?", options: ["HTTP", "DNS", "SMTP", "FTP"], correct: 2 },
                    { id: 9, question: "Which part of the URL identifies the server?", options: ["Protocol", "Domain name", "Path", "Query string"], correct: 2 },
                    { id: 10, question: "In client–server architecture, who initiates the communication?", options: ["Server", "Client", "Both", "None"], correct: 2 },
                    { id: 11, question: "What is the maximum number of unique IPv4 addresses?", options: ["2^16", "2^32", "2^64", "2^128"], correct: 2 },
                    { id: 12, question: "Which of these is an example of a top-level domain (TLD)?", options: [".com", "example.com", "www.example.com", "http://example.com"], correct: 1 },
                    { id: 13, question: "What is the loopback IP address in IPv4?", options: ["127.0.0.1", "192.168.0.1", "10.0.0.1", "0.0.0.0"], correct: 1 },
                    { id: 14, question: "Which of the following IP addresses is reserved for APIPA (Automatic Private IP Addressing)?", options: ["169.254.x.x", "10.x.x.x", "172.16.x.x", "192.168.x.x"], correct: 1 },
                    { id: 15, question: "What does URL stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Uniform Retrieval Location", "Universal Retrieval Locator"], correct: 2 },
                    { id: 16, question: "Which protocol is commonly used in client–server email communication?", options: ["SMTP", "IMAP", "POP3", "All of these"], correct: 4 },
                    { id: 17, question: "Which type of IP address is manually configured?", options: ["Dynamic IP", "Static IP", "Private IP", "Reserved IP"], correct: 2 },
                    { id: 18, question: "In client-server, which one provides resources?", options: ["Client", "Server", "Both", "Router"], correct: 2 },
                    { id: 19, question: "What is the default port of HTTP?", options: ["21", "25", "80", "443"], correct: 3 },
                    { id: 20, question: "What is the default port of HTTPS?", options: ["110", "143", "443", "8080"], correct: 3 },

                    { id: 21, question: "Which IP class provides the largest number of host addresses?", options: ["Class A", "Class B", "Class C", "Class D"], correct: 1 },
                    { id: 22, question: "Which of the following is NOT a valid IP address?", options: ["192.168.0.1", "256.1.1.1", "10.0.0.5", "8.8.8.8"], correct: 2 },
                    { id: 23, question: "What does the hostname 'localhost' refer to?", options: ["Your own computer", "Remote computer", "DNS server", "Web server"], correct: 1 },
                    { id: 24, question: "Which protocol is used to assign IP addresses automatically?", options: ["DNS", "DHCP", "NAT", "FTP"], correct: 2 },
                    { id: 25, question: "Which layer of TCP/IP model deals with IP addressing?", options: ["Application", "Transport", "Internet", "Network Access"], correct: 3 },
                    { id: 26, question: "What is the function of NAT (Network Address Translation)?", options: ["Translate domain names", "Translate private IP to public IP", "Encrypt messages", "Assign MAC addresses"], correct: 2 },
                    { id: 27, question: "Which of the following identifies a specific computer on the internet?", options: ["Domain name", "IP address", "MAC address", "All of these"], correct: 2 },
                    { id: 28, question: "What does FQDN stand for?", options: ["Fully Qualified Domain Name", "Fast Query Domain Name", "Fixed Qualified Domain Number", "Free Query Domain Node"], correct: 1 },
                    { id: 29, question: "Which organization manages domain names globally?", options: ["IEEE", "IETF", "ICANN", "W3C"], correct: 3 },
                    { id: 30, question: "What is the default subnet mask for Class B?", options: ["255.255.0.0", "255.0.0.0", "255.255.255.0", "255.255.255.255"], correct: 1 },

                    { id: 31, question: "Which of the following is NOT part of a URL?", options: ["Protocol", "Domain", "Subnet mask", "Path"], correct: 3 },
                    { id: 32, question: "Which protocol is primarily used for resolving hostnames to IP?", options: ["SMTP", "FTP", "DNS", "HTTP"], correct: 3 },
                    { id: 33, question: "What is the main purpose of IP addressing?", options: ["Identify devices", "Encrypt data", "Provide routing", "Connect to DNS"], correct: 1 },
                    { id: 34, question: "Which of these is an IPv6 address format?", options: ["192.168.1.1", "10.0.0.1", "2001:0db8::1", "127.0.0.1"], correct: 3 },
                    { id: 35, question: "How many octets are in an IPv4 address?", options: ["2", "4", "6", "8"], correct: 2 },
                    { id: 36, question: "What does the client do in client-server architecture?", options: ["Provide resources", "Request services", "Manage DNS", "Assign IP addresses"], correct: 2 },
                    { id: 37, question: "Which of these is an example of a client?", options: ["Web browser", "Web server", "Mail server", "DNS server"], correct: 1 },
                    { id: 38, question: "Which of the following is an example of a server?", options: ["Google Chrome", "Apache", "Firefox", "Outlook"], correct: 2 },
                    { id: 39, question: "Which IP version uses hexadecimal representation?", options: ["IPv4", "IPv6", "Both", "None"], correct: 2 },
                    { id: 40, question: "Which of these is the correct format of IPv4?", options: ["Decimal dotted", "Hexadecimal dotted", "Binary dotted", "Octal dotted"], correct: 1 },

                    { id: 41, question: "Which IP class is reserved for experimental purposes?", options: ["Class A", "Class B", "Class C", "Class E"], correct: 4 },
                    { id: 42, question: "What is the default port of DNS?", options: ["21", "25", "53", "80"], correct: 3 },
                    { id: 43, question: "Which of the following IPs is a broadcast address for 192.168.1.0/24?", options: ["192.168.1.0", "192.168.1.1", "192.168.1.255", "192.168.1.254"], correct: 3 },
                    { id: 44, question: "Which one is NOT a valid top-level domain?", options: [".org", ".net", ".abc", ".edu"], correct: 3 },
                    { id: 45, question: "Which protocol is used for mapping IP to MAC?", options: ["DNS", "ARP", "DHCP", "NAT"], correct: 2 },
                    { id: 46, question: "Which IP class supports 16 million hosts?", options: ["Class A", "Class B", "Class C", "Class D"], correct: 1 },
                    { id: 47, question: "What is the maximum length of a domain name?", options: ["128 characters", "256 characters", "63 characters", "255 characters"], correct: 4 },
                    { id: 48, question: "What is the maximum number of characters in each domain label?", options: ["32", "63", "128", "255"], correct: 2 },
                    { id: 49, question: "Which record in DNS maps a domain to an IP?", options: ["MX record", "A record", "CNAME record", "NS record"], correct: 2 },
                    { id: 50, question: "Which record type in DNS is used for mail servers?", options: ["MX record", "A record", "CNAME record", "PTR record"], correct: 1 },

                    { id: 51, question: "Which of these is an example of a domain?", options: ["192.168.1.1", "example.com", "ftp://example.com", "http://localhost"], correct: 2 },
                    { id: 52, question: "Which device usually provides DHCP service?", options: ["Switch", "Router", "Firewall", "Hub"], correct: 2 },
                    { id: 53, question: "What is the binary equivalent of IP 192.168.1.1 (first octet only)?", options: ["11000000", "10101000", "00000001", "11111111"], correct: 1 },
                    { id: 54, question: "What is the default port of DHCP?", options: ["67/68", "25", "53", "110"], correct: 1 },
                    { id: 55, question: "Which protocol is used in client-server for web communication?", options: ["HTTP", "SMTP", "FTP", "POP3"], correct: 1 },
                    { id: 56, question: "Which protocol helps translate URLs into IP addresses?", options: ["DHCP", "DNS", "NAT", "IMAP"], correct: 2 },
                    { id: 57, question: "What is the full form of DNS?", options: ["Domain Name System", "Data Network Service", "Distributed Name Service", "Domain Numbering System"], correct: 1 },
                    { id: 58, question: "Which address uniquely identifies a network interface?", options: ["Domain name", "IP address", "MAC address", "Subnet"], correct: 3 },
                    { id: 59, question: "Which service ensures a client gets the same IP every time?", options: ["Dynamic IP", "Static IP", "Reserved DHCP", "Random IP"], correct: 3 },
                    { id: 60, question: "Which client-server model example is correct?", options: ["Web browser - Web server", "Switch - Router", "IP - DNS", "Firewall - Hub"], correct: 1 },

                    { id: 61, question: "Which address is used by a device to communicate within its own network?", options: ["Private IP", "Public IP", "Broadcast IP", "Gateway IP"], correct: 1 },
                    { id: 62, question: "What is the purpose of subnetting?", options: ["Increase speed", "Divide a network into smaller parts", "Encrypt data", "Translate IP addresses"], correct: 2 },
                    { id: 63, question: "What is the default gateway used for?", options: ["Local communication", "External communication", "DNS resolution", "Subnetting"], correct: 2 },
                    { id: 64, question: "Which of the following is NOT an application of client-server?", options: ["Email", "Web browsing", "File sharing", "Broadcast TV"], correct: 4 },
                    { id: 65, question: "Which IP address range is reserved for loopback testing?", options: ["0.0.0.0/8", "127.0.0.0/8", "169.254.0.0/16", "192.168.0.0/16"], correct: 2 },
                    { id: 66, question: "What does DHCP stand for?", options: ["Dynamic Host Configuration Protocol", "Data Host Control Protocol", "Domain Host Configuration Process", "Distributed Host Control Protocol"], correct: 1 },
                    { id: 67, question: "Which device translates private IP to public IP?", options: ["Switch", "Router", "Hub", "Firewall"], correct: 2 },
                    { id: 68, question: "Which URL component specifies the communication protocol?", options: ["http://", "www", "domain.com", "/path"], correct: 1 },
                    { id: 69, question: "Which is the reserved IPv6 loopback address?", options: ["::1", "::0", "ffff::", "2001::"], correct: 1 },
                    { id: 70, question: "Which command is used to check IP address in Windows?", options: ["ipconfig", "ifconfig", "ping", "netstat"], correct: 1 },

                    { id: 71, question: "Which command is used to test connectivity between client and server?", options: ["ping", "ipconfig", "tracert", "nslookup"], correct: 1 },
                    { id: 72, question: "Which client-server model does Email use?", options: ["SMTP - Client", "SMTP - Server", "POP3/IMAP - Client & SMTP - Server", "HTTP only"], correct: 3 },
                    { id: 73, question: "Which of these is NOT a private IP range?", options: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "11.0.0.0/8"], correct: 4 },
                    { id: 74, question: "Which device usually stores DNS records?", options: ["Router", "Switch", "DNS server", "Firewall"], correct: 3 },
                    { id: 75, question: "Which IP address format is human-readable?", options: ["Binary", "Hexadecimal", "Dotted decimal", "Octal"], correct: 3 },
                    { id: 76, question: "What is the purpose of a domain registrar?", options: ["Assign IPs", "Manage DNS", "Register domain names", "Provide emails"], correct: 3 },
                    { id: 77, question: "Which component of URL specifies the location of a resource?", options: ["Protocol", "Domain", "Path", "Port"], correct: 3 },
                    { id: 78, question: "Which IP address range is public?", options: ["192.168.x.x", "10.x.x.x", "172.16.x.x – 172.31.x.x", "8.8.8.8"], correct: 4 },
                    { id: 79, question: "Which is the correct mapping in client-server?", options: ["Client provides, server requests", "Server requests, client provides", "Client requests, server provides", "Both request simultaneously"], correct: 3 },
                    { id: 80, question: "Which of these is a valid IPv6 address?", options: ["2001:db8::1", "192.168.300.1", "172.16.256.1", "123.456.78.9"], correct: 1 }
                ],
            },
            "Network devices: hub, switch, router, modem, access point": {
                color: "#D946EF",
                questions: [
                    { id: 1, question: "Which network device operates at the physical layer of OSI model?", options: ["Router", "Switch", "Hub", "Access Point"], correct: 3 },
                    { id: 2, question: "Which device is known as a multiport repeater?", options: ["Hub", "Switch", "Router", "Modem"], correct: 1 },
                    { id: 3, question: "Which device uses MAC addresses to forward data?", options: ["Router", "Switch", "Hub", "Modem"], correct: 2 },
                    { id: 4, question: "Which device connects two different networks?", options: ["Switch", "Hub", "Router", "Access Point"], correct: 3 },
                    { id: 5, question: "Which device converts digital signals into analog and vice versa?", options: ["Switch", "Hub", "Router", "Modem"], correct: 4 },
                    { id: 6, question: "Which device provides wireless connectivity in a network?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 7, question: "Which device broadcasts data to all connected devices?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 8, question: "Which device reduces network collisions by creating separate collision domains?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 9, question: "Which device assigns IP addresses dynamically?", options: ["Modem", "Router", "Hub", "Switch"], correct: 2 },
                    { id: 10, question: "Which device is used to connect a LAN to the internet?", options: ["Switch", "Hub", "Router", "Modem"], correct: 4 },
                    { id: 11, question: "Which device works on data link layer and network layer?", options: ["Router", "Hub", "Switch", "Access Point"], correct: 1 },
                    { id: 12, question: "Which device creates multiple broadcast domains?", options: ["Hub", "Router", "Switch", "Access Point"], correct: 2 },
                    { id: 13, question: "Which device uses IP addresses for packet forwarding?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 14, question: "Which device is commonly used in star topology?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 15, question: "Which device only works at Layer 1 of OSI model?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 3 },
                    { id: 16, question: "Which device connects wireless clients to a wired network?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 4 },
                    { id: 17, question: "Which device is considered more intelligent, hub or switch?", options: ["Hub", "Switch", "Router", "Modem"], correct: 2 },
                    { id: 18, question: "Which device is used for packet filtering and forwarding?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 19, question: "Which device helps reduce network congestion compared to hubs?", options: ["Router", "Switch", "Access Point", "Modem"], correct: 2 },
                    { id: 20, question: "Which device works on Layer 2 and sometimes Layer 3 of OSI?", options: ["Hub", "Switch", "Router", "Modem"], correct: 2 },
                    { id: 21, question: "Which device allows multiple users to share an internet connection?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 22, question: "Which device strengthens weak signals in a network?", options: ["Switch", "Router", "Hub", "Repeater"], correct: 4 },
                    { id: 23, question: "Which device can act as a DHCP server?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 24, question: "Which device is used in wireless LANs?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 25, question: "Which device provides routing between two different networks?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 2 },
                    { id: 26, question: "Which device is prone to collisions due to broadcasting?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 27, question: "Which device is used for packet switching?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 28, question: "Which device can connect a LAN to a WAN?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 2 },
                    { id: 29, question: "Which device assigns private IP addresses in a home network?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 30, question: "Which device is used for wireless hotspot creation?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 4 },
                    { id: 31, question: "Which device works with CSMA/CD protocol?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 32, question: "Which device reduces unnecessary traffic by forwarding only to intended devices?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 33, question: "Which device contains a default gateway configuration?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 34, question: "Which device is considered the brain of a home network?", options: ["Switch", "Hub", "Router", "Modem"], correct: 3 },
                    { id: 35, question: "Which device can perform both wired and wireless functions?", options: ["Router", "Switch", "Hub", "Access Point"], correct: 1 },
                    { id: 36, question: "Which device splits an internet connection among multiple users?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 37, question: "Which device creates a collision domain for each port?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 38, question: "Which device can perform NAT (Network Address Translation)?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 39, question: "Which device is used to connect wireless printers to a LAN?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 40, question: "Which device uses store-and-forward technique?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 41, question: "Which device helps prevent data collisions by using buffers?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 42, question: "Which device is faster in data transfer, hub or switch?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 43, question: "Which device decides the best path for data packets?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 44, question: "Which device can isolate broadcast domains?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 45, question: "Which device provides both wired and wireless connections?", options: ["Router", "Switch", "Hub", "Access Point"], correct: 1 },
                    { id: 46, question: "Which device uses ARP (Address Resolution Protocol)?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 47, question: "Which device connects to the ISP for internet service?", options: ["Hub", "Switch", "Router", "Modem"], correct: 4 },
                    { id: 48, question: "Which device is also called a concentrator?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 49, question: "Which device reduces collisions using full-duplex mode?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 50, question: "Which device provides wireless authentication?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 51, question: "Which device maintains a MAC address table?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 52, question: "Which device can also act as a firewall?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 53, question: "Which device transmits signals without filtering?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 54, question: "Which device forwards packets based on IP address?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 55, question: "Which device often combines modem and router functions?", options: ["Hub", "Switch", "Router", "Gateway"], correct: 3 },
                    { id: 56, question: "Which device increases the number of available Ethernet ports?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 57, question: "Which device supports VLANs?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 58, question: "Which device handles both wired and wireless clients?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 59, question: "Which device has the least intelligence?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 60, question: "Which device manages IP addressing in home networks?", options: ["Switch", "Router", "Hub", "Access Point"], correct: 2 },
                    { id: 61, question: "Which device extends wireless network coverage?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 62, question: "Which device enables device-to-device communication in wireless LAN?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 63, question: "Which device creates a single collision domain for all ports?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 64, question: "Which device is necessary for broadband internet?", options: ["Hub", "Switch", "Router", "Modem"], correct: 4 },
                    { id: 65, question: "Which device connects LAN segments?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 66, question: "Which device separates traffic using MAC filtering?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 67, question: "Which device is also known as a wireless bridge?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 68, question: "Which device increases bandwidth by dividing traffic intelligently?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 69, question: "Which device supports packet inspection?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 70, question: "Which device is often integrated with firewall features?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 71, question: "Which device prevents collisions by using a buffer per port?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 72, question: "Which device is essential for Wi-Fi networks?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 73, question: "Which device checks destination MAC address before forwarding?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                    { id: 74, question: "Which device establishes connection with ISP line?", options: ["Hub", "Switch", "Router", "Modem"], correct: 4 },
                    { id: 75, question: "Which device uses NAT for internet sharing?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 76, question: "Which device operates at Layer 3 of OSI?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 77, question: "Which device prevents broadcast storms?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 3 },
                    { id: 78, question: "Which device has only Layer 1 functionality?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 1 },
                    { id: 79, question: "Which device can provide wireless guest networks?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 4 },
                    { id: 80, question: "Which device improves performance using microsegmentation?", options: ["Hub", "Switch", "Router", "Access Point"], correct: 2 },
                ],
            },
            "Internet services: web, email, cloud storage; browsers, search basics": {
                color: "#F43F5E",
                questions: [

                    { id: 1, question: "Which protocol is primarily used for sending emails?", options: ["HTTP", "SMTP", "FTP", "IMAP"], correct: 2 },
                    { id: 2, question: "Which protocol is used to retrieve emails from a server?", options: ["SMTP", "POP3", "DNS", "ICMP"], correct: 2 },
                    { id: 3, question: "Which of the following is NOT an email protocol?", options: ["IMAP", "POP3", "SMTP", "TCP"], correct: 4 },
                    { id: 4, question: "Which service allows you to store files online and access them anywhere?", options: ["Cloud storage", "Email", "FTP", "DNS"], correct: 1 },
                    { id: 5, question: "Google Drive, Dropbox, and OneDrive are examples of:", options: ["Browsers", "Cloud storage services", "Web servers", "Search engines"], correct: 2 },
                    { id: 6, question: "Which of the following is an example of a web browser?", options: ["Google Chrome", "Google Drive", "Yahoo Mail", "Dropbox"], correct: 1 },
                    { id: 7, question: "Which of the following is a search engine?", options: ["Gmail", "Google", "Yahoo Mail", "Outlook"], correct: 2 },
                    { id: 8, question: "The service used to view web pages on the internet is called:", options: ["Browser", "Cloud storage", "Email client", "FTP"], correct: 1 },
                    { id: 9, question: "What does IMAP stand for?", options: ["Internet Mail Access Protocol", "Internal Mail Application Protocol", "Internet Messaging Access Process", "Input Mail Access Program"], correct: 1 },
                    { id: 10, question: "Which browser was developed by Microsoft?", options: ["Firefox", "Chrome", "Edge", "Safari"], correct: 3 },
                    { id: 11, question: "Which is NOT a cloud storage service?", options: ["Dropbox", "OneDrive", "Google Drive", "Gmail"], correct: 4 },
                    { id: 12, question: "Which protocol does a web browser use to request a web page?", options: ["FTP", "SMTP", "HTTP/HTTPS", "IMAP"], correct: 3 },
                    { id: 13, question: "Yahoo Mail is an example of:", options: ["Cloud storage", "Email service", "Search engine", "Browser"], correct: 2 },
                    { id: 14, question: "Which company developed the Safari browser?", options: ["Google", "Microsoft", "Apple", "Mozilla"], correct: 3 },
                    { id: 15, question: "Which of the following is a popular open-source browser?", options: ["Firefox", "Chrome", "Edge", "Safari"], correct: 1 },
                    { id: 16, question: "Which protocol is used for secure communication over the web?", options: ["HTTP", "HTTPS", "FTP", "SMTP"], correct: 2 },
                    { id: 17, question: "Which search engine is owned by Microsoft?", options: ["Google", "Bing", "Yahoo", "DuckDuckGo"], correct: 2 },
                    { id: 18, question: "What is the purpose of a search engine?", options: ["Store files", "Send emails", "Find information on the internet", "Browse offline"], correct: 3 },
                    { id: 19, question: "Which cloud storage service is integrated with Microsoft Office?", options: ["Dropbox", "iCloud", "OneDrive", "Google Drive"], correct: 3 },
                    { id: 20, question: "Which is NOT a search engine?", options: ["Bing", "Google", "Outlook", "DuckDuckGo"], correct: 3 },
                    { id: 21, question: "Which email service is provided by Google?", options: ["Yahoo Mail", "Gmail", "Hotmail", "ProtonMail"], correct: 2 },
                    { id: 22, question: "The extension '.com' in a website indicates:", options: ["Government", "Commercial", "Organization", "Network"], correct: 2 },
                    { id: 23, question: "Which browser is developed by Mozilla Foundation?", options: ["Chrome", "Firefox", "Edge", "Safari"], correct: 2 },
                    { id: 24, question: "Which of the following is a desktop email client?", options: ["Outlook", "Gmail", "Yahoo Mail", "Google Drive"], correct: 1 },
                    { id: 25, question: "Which is the largest search engine worldwide?", options: ["Yahoo", "Google", "Bing", "DuckDuckGo"], correct: 2 },
                    { id: 26, question: "Which protocol is used for transferring files?", options: ["SMTP", "FTP", "IMAP", "POP3"], correct: 2 },
                    { id: 27, question: "Which browser feature helps in saving frequently visited websites?", options: ["Tabs", "Bookmarks", "History", "Cache"], correct: 2 },
                    { id: 28, question: "Which company owns YouTube?", options: ["Microsoft", "Apple", "Google", "Yahoo"], correct: 3 },
                    { id: 29, question: "What is the main purpose of cloud storage?", options: ["Store and access files remotely", "Send emails", "Browse the internet", "Stream videos"], correct: 1 },
                    { id: 30, question: "Which is NOT an email provider?", options: ["Gmail", "Outlook", "Dropbox", "Yahoo Mail"], correct: 3 },
                    { id: 31, question: "Which search engine focuses on user privacy?", options: ["Google", "Bing", "DuckDuckGo", "Yahoo"], correct: 3 },
                    { id: 32, question: "What is the role of cache in a browser?", options: ["Speed up page loading", "Store emails", "Send data", "Provide security"], correct: 1 },
                    { id: 33, question: "Which of the following is an email protocol for retrieving messages?", options: ["SMTP", "POP3", "DNS", "ARP"], correct: 2 },
                    { id: 34, question: "Which cloud service is offered by Apple?", options: ["Google Drive", "iCloud", "Dropbox", "OneDrive"], correct: 2 },
                    { id: 35, question: "Which of these is NOT a web browser?", options: ["Opera", "Edge", "Chrome", "Bing"], correct: 4 },
                    { id: 36, question: "Which search engine is known for open-source indexing?", options: ["Google", "Bing", "DuckDuckGo", "Yahoo"], correct: 3 },
                    { id: 37, question: "Which email protocol allows access from multiple devices?", options: ["POP3", "IMAP", "SMTP", "FTP"], correct: 2 },
                    { id: 38, question: "What is the role of a web browser?", options: ["Send emails", "View web pages", "Store files", "Run servers"], correct: 2 },
                    { id: 39, question: "Which is NOT an example of an internet service?", options: ["Email", "Cloud storage", "Web browsing", "CPU scheduling"], correct: 4 },
                    { id: 40, question: "Which browser uses the WebKit engine?", options: ["Edge", "Chrome", "Safari", "Firefox"], correct: 3 },
                    { id: 41, question: "Which search engine was one of the earliest on the web?", options: ["Lycos", "Bing", "Google", "DuckDuckGo"], correct: 1 },
                    { id: 42, question: "Which company developed Gmail?", options: ["Apple", "Microsoft", "Google", "Yahoo"], correct: 3 },
                    { id: 43, question: "Which browser introduced the Incognito/Private browsing mode?", options: ["Safari", "Chrome", "Firefox", "Edge"], correct: 2 },
                    { id: 44, question: "Which of the following is an example of a cloud-based email service?", options: ["MS Outlook", "Yahoo Mail", "Gmail", "All of these"], correct: 4 },
                    { id: 45, question: "Which is the default search engine of Chrome?", options: ["Bing", "Yahoo", "Google", "DuckDuckGo"], correct: 3 },
                    { id: 46, question: "What is the role of an email client?", options: ["Send and receive emails", "Store files", "Browse internet", "Search engines"], correct: 1 },
                    { id: 47, question: "Which browser is pre-installed on Apple devices?", options: ["Safari", "Edge", "Chrome", "Firefox"], correct: 1 },
                    { id: 48, question: "Which of the following stores browsing history?", options: ["Search engine", "Cloud storage", "Browser", "Server"], correct: 3 },
                    { id: 49, question: "Which cloud storage service is most used worldwide?", options: ["OneDrive", "Google Drive", "Dropbox", "iCloud"], correct: 2 },
                    { id: 50, question: "Which service allows text, audio, and video communication online?", options: ["Email", "Chat", "FTP", "DNS"], correct: 2 },
                    { id: 51, question: "Which search engine is owned by Yahoo?", options: ["AltaVista", "Bing", "DuckDuckGo", "Yahoo Search"], correct: 4 },
                    { id: 52, question: "Which feature of browsers allows multiple websites to be open at once?", options: ["Tabs", "Bookmarks", "Cache", "History"], correct: 1 },
                    { id: 53, question: "Which of the following is NOT an internet browser?", options: ["Opera", "Safari", "Netscape", "WhatsApp"], correct: 4 },
                    { id: 54, question: "Which protocol is used for sending email messages?", options: ["POP3", "SMTP", "IMAP", "HTTP"], correct: 2 },
                    { id: 55, question: "Which company owns the Edge browser?", options: ["Apple", "Mozilla", "Microsoft", "Google"], correct: 3 },
                    { id: 56, question: "What is the main function of search engines?", options: ["Store emails", "Retrieve web information", "Browse offline", "Transfer files"], correct: 2 },
                    { id: 57, question: "Which is NOT a cloud service provider?", options: ["Google Drive", "Dropbox", "YouTube", "OneDrive"], correct: 3 },
                    { id: 58, question: "Which is an example of an email domain?", options: ["@gmail.com", "http://www.google.com", "ftp://server", "cloudstorage.net"], correct: 1 },
                    { id: 59, question: "Which is an example of an instant messaging service?", options: ["WhatsApp", "Outlook", "Yahoo Mail", "Chrome"], correct: 1 },
                    { id: 60, question: "What is the role of cookies in browsers?", options: ["Save browsing data", "Send emails", "Store files", "Prevent hacking"], correct: 1 },
                    { id: 61, question: "Which search engine is considered open-source?", options: ["Google", "YaCy", "Bing", "Yahoo"], correct: 2 },
                    { id: 62, question: "Which email service was originally called Hotmail?", options: ["Yahoo Mail", "Gmail", "Outlook", "ProtonMail"], correct: 3 },
                    { id: 63, question: "Which browser is available on Linux by default?", options: ["Firefox", "Chrome", "Safari", "Edge"], correct: 1 },
                    { id: 64, question: "Which cloud storage is available for iOS users?", options: ["OneDrive", "Dropbox", "iCloud", "Google Drive"], correct: 3 },
                    { id: 65, question: "Which company developed the Chrome browser?", options: ["Apple", "Mozilla", "Google", "Microsoft"], correct: 3 },
                    { id: 66, question: "Which search engine was founded by Larry Page and Sergey Brin?", options: ["Yahoo", "Bing", "Google", "DuckDuckGo"], correct: 3 },
                    { id: 67, question: "Which protocol encrypts data for secure email transmission?", options: ["SSL/TLS", "FTP", "POP3", "HTTP"], correct: 1 },
                    { id: 68, question: "Which browser extension is used to block ads?", options: ["uBlock", "Drive", "Gmail", "Search"], correct: 1 },
                    { id: 69, question: "Which of the following is NOT a feature of cloud storage?", options: ["Access anywhere", "Automatic backup", "Local-only access", "File sharing"], correct: 3 },
                    { id: 70, question: "Which browser is fastest according to most benchmarks?", options: ["Chrome", "Firefox", "Safari", "Edge"], correct: 1 },
                    { id: 71, question: "Which search engine is most used in China?", options: ["Google", "Bing", "Baidu", "DuckDuckGo"], correct: 3 },
                    { id: 72, question: "Which of the following is an example of a metasearch engine?", options: ["Google", "Dogpile", "Bing", "Yahoo"], correct: 2 },
                    { id: 73, question: "Which protocol allows retrieval of emails while keeping them on the server?", options: ["POP3", "IMAP", "SMTP", "FTP"], correct: 2 },
                    { id: 74, question: "Which browser is focused on privacy and blocks trackers?", options: ["Chrome", "Firefox", "Brave", "Edge"], correct: 3 },
                    { id: 75, question: "Which company owns the Android Play Store?", options: ["Microsoft", "Google", "Apple", "Amazon"], correct: 2 },
                    { id: 76, question: "Which search engine was originally called BackRub?", options: ["Google", "Yahoo", "Bing", "Lycos"], correct: 1 },
                    { id: 77, question: "Which of the following is NOT an email service provider?", options: ["ProtonMail", "Zoho Mail", "Bing", "Yahoo Mail"], correct: 3 },
                    { id: 78, question: "Which is an example of an open-source cloud storage platform?", options: ["Nextcloud", "Dropbox", "OneDrive", "Google Drive"], correct: 1 },
                    { id: 79, question: "Which is the most widely used browser worldwide?", options: ["Firefox", "Chrome", "Safari", "Edge"], correct: 2 },
                    { id: 80, question: "Which feature of cloud storage enables multiple users to edit the same file?", options: ["File syncing", "Version history", "Collaboration", "Backup"], correct: 3 }


                ]
            },
        },
    
};

export default computerNextwork;
